### ISSUE TITLE
DNS validation

### ISSUE THREAD

**Issue by batooo** [fszlin/certes#1]
I tried almost all combinations but cant make it works.

```
// Comptue key authorization for dns-01
dnsChallenge = authz.Data.Challenges.First(c => c.Type == ChallengeTypes.Dns01);
keyAuthString = client.ComputeKeyAuthorization(dnsChallenge);

// Do something to fullfill the challenge,
// e.g. upload key auth string to well known path, or make changes to DNS
```

Let`s say i try to get certificate for "test.example.com" where "example.com" is registered domain.

I tried to create txt record with keyAuthString value in
`_acme-challenge.test.example.com`
but process is always failed.

Can you give example how does this works?

**Comment by fszlin** [comment]
Could you confirm you are using the SHA-256 digest of the key authorization for the DNS record?

You may get the DNS value using this:
```csharp
    var keyAuthBytes = Encoding.UTF8.GetBytes(keyAuthString);
    var sha256 = new Sha256Digest();
    var hashed = new byte[sha256.GetDigestSize()];

    sha256.BlockUpdate(keyAuthBytes, 0, keyAuthBytes.Length);
    sha256.DoFinal(hashed, 0);

    var dnsValue = JwsConvert.ToBase64String(hashed);
```

**Comment by batooo** [comment]
Yeah now its working. Few suggestions:

- Add this into your documentation for future clients
- Maybe make nuget package to be able to use this package outside **.NET CORE**

**Comment by batooo** [comment]
Also in your usage example you try to add "CN" uppercase but in Closte.AcmeClient.Pkcs.AddName:

X509Name.DefaultLookup.Contains("CN") = false
X509Name.DefaultLookup.Contains("cn") = true

**Comment by fszlin** [comment]
The nuget package should work with .NET Framework 4.6+, as it is targeting netstandard1.3. Feel free to submit an issue if not.

I am not sure about **Closte**, but I think the symbols are uppercase in RFC2253 and RFC1779. And I think **Org.BouncyCastle.Asn1.X509.X509Name.DefaultLookup** using lowercase is merely for easier lookup.

**Comment by batooo** [comment]
Its "Closte" since i rewrite it for my .net 4.5.2 project. At least in 4.5.2 they are all lowercase, that is what i saw in debugger.

**Comment by fszlin** [comment]
You can compile it for .NET 4.5 by using something like this in project.json:
```json
"dependencies": {
  "Newtonsoft.Json": "9.0.1",
  "Portable.BouncyCastle": "1.8.1.1"
},
"frameworks": {
  "netstandard1.3": {
    "dependencies": {
      "System.Net.Http": "4.1.0",
      "System.Runtime.InteropServices": "4.1.0"
    }
  },
  "net45": {
    "frameworkAssemblies": {
      "System.Net.Http": ""
    }
  }
}
```
