### ISSUE TITLE
Getting AcmeRequestException: Fail to load resource from...

### ISSUE THREAD

**Issue by koravl** [fszlin/certes#109]
Hi, 
I'm getting AcmeRequestException: Fail to load resource from 'https://acme-staging-v02.api.letsencrypt.org/acme/new-acct' 

at line

`var order = await acme.NewOrder(new[] { "some.domain.net" });`

How to understand what's I'm doing wrong?

**Comment by fszlin** [comment]
Not a good message. 😞 

I think what happened is `acme` could not fetch your ACME account by the given key.
Have you done the registration process?

**Comment by koravl** [comment]
Yes, registration done. I've fetched sources instead of nuget and found where error happens: in method AcmeHttpClient.Post<T>. Error message is "urn:ietf:params:acme:error:accountDoesNotExist" as you said, but I've registered first and saved pemKey. Then I do following as written in example:

```
var pemKey = File.ReadAllText("AcmeAccountPemKey.txt");
var accountKey = KeyFactory.FromPem(pemKey);
var acme = new AcmeContext(WellKnownServers.LetsEncryptStagingV2, accountKey);
var account = acme.Account();
var order = await acme.NewOrder(new[] { "some.domain.net" });
```

It'd be more convenient if inner exception contained more precize error message, e.g. message from letencrypt.

Now I'll make some expreriments and then will write results.

**Comment by koravl** [comment]
In creating account example I made app to wait for end of account creation process and only then save pem to file. After that, error dissapeared. May be it is coincidence, may be not.

var acme = new AcmeContext(WellKnownServers.LetsEncryptStagingV2);
var account = acme.NewAccount("email@gmail.com", true)**.GetAwaiter().GetResult();**
var pemKey = acme.AccountKey.ToPem();
File.WriteAllText("AcmeAccountPemKey.txt", pemKey);

I noticed, that requests are processed quite long time, may me acme.AccountKey.ToPem returns before account created with incorrect value?

**Comment by fszlin** [comment]
Yes, you need to wait for the task to complete. If you exit before the task complete, the `NewAccount` request to Let's Encrypt will get canceled.

It may be better if you do `var account = await acme.NewAccount("email@gmail.com", true);`?

**Comment by koravl** [comment]
Yes. But to prevent misunderstanding, acme.AccountKey.ToPem() should not return before account created.

**Comment by fszlin** [comment]
I agree with you in this use case. Just in general `AcmeContext.AccountKey` is the key pair associated with the context, it could be an existing key, new key, or custom key generate by OpenSSL. So, it cannot guarantee a valid and active account exists.
