### ISSUE TITLE
Design v2 API

### ISSUE THREAD

**Issue by fszlin** [fszlin/certes#11]
Need to design new client APIs for the [upcoming LE v2 endpoint]( https://letsencrypt.org/2017/06/14/acme-v2-api.html).

V1 APIs should remain intact as long as LE supports v1 endpoint.

**Comment by webprofusion-chrisc** [comment]
HI, I'm currently looking at using Certes as a v2 ACME Provider in Certify SSL Manager. Regarding the API, how do you start a new authorization when a previous (http-01) authorization has failed? The v2 docs suggest an authorizations.New() method but I can't find that.

**Comment by fszlin** [comment]
The API doc is a bit outdated, and I will update it soon.

Regarding the new-authz, it is an optional endpoint per [spec]( https://tools.ietf.org/html/draft-ietf-acme-acme-09#section-7.4.1). I don’t think boulder has implemented it.

I believe we are supposed to create a new order if any authorization failed. As you aware, currently there’s a [bug](https://github.com/letsencrypt/boulder/issues/3333) preventing new order with failed authz.

**Comment by webprofusion-chrisc** [comment]
Thanks Eddie, I have a semi-working http-01 provider in Certify using Certes now: https://github.com/webprofusion/certify/blob/vnext4.0/src/Certify.Providers.Certes/CertesACMEProvider.cs

As DNS challenges are not basically essential I just need to figure out how I'm going to talk to all the different DNS providers from one codebase :)

**Comment by webprofusion-chrisc** [comment]
Hi Eddie, just for info, wildcard domains such as *.test.com currently get auto added as SAN names and this results in an ACME error along the lines of 'CSR contains domains not in Order', so as an alternative to part of IOrderContextExtension.Finalize I have a check which doesn't add the SAN name if it's part of the wildcard:

```CSharp
                        if (config.PrimaryDomain != $"*.{authz.Identifier.Value}")
                        {
                            //only add domain to SAN if it is not derived from a wildcard domain eg test.com from *.test.com
                            builder.SubjectAlternativeNames.Add(authz.Identifier.Value);
                        }

```

I'm not sure what the proper fix for this is with regards to Certes but I thought I'd pass it on.

**Comment by fszlin** [comment]
Hi @webprofusion-chrisc, thanks for letting me know.
I was under the impression SAN [should contain all domains](https://tools.ietf.org/html/rfc2818#section-3.1) 🤕

**Comment by webprofusion-chrisc** [comment]
Yes, so was I (I think most browsers now would reject a cert if it didn't include all domains in the SAN list) but I don't know the distinctions around wildcards. I have yet to try requesting a multi domain SAN cert through the v2 API yet.

**Comment by webprofusion-chrisc** [comment]
Actually, on further investigation I got this the wrong way round, instead of adding authz.Identifier.Value to the SANs list you need to add the original wildcard domain ("*.test.com"), the authz.Identifier.Value is stripped of the *. prefix so is just" test.com" and is therefore not valid against the *.test.com Order.

**Comment by fszlin** [comment]
ah, that's the reason.
May be it is better to use order.Identifiers. The authz object also has `wildcard` property, but it is not in the spec.

**Comment by cpu** [comment]
@webprofusion-chrisc Glad you figured it out :-) 

> May be it is better to use order.Identifiers.

Agreed. The spec specifically forbids putting the `*.` in an authorization identifier so it will never match the order's identifiers if the order's identifiers included a wildcard name:
```
 An authorization returned by the server for a wildcard domain name identifier MUST NOT include the asterisk and full stop ("_[RFC5280].") prefix in the authorization identifier value.
```

> The authz object also has wildcard property, but it is not in the spec.

Indeed. That's on my TODO list to bring to the WG list for discussion. I think there's two approaches:
1. Adding the `Wildcard` bool on the authz to the spec. I think it's important to have a way to understand that the identifier `example.com` in an authz was created for an order identifier `*.example.com`.
2. Removing the restriction on the authorization not allowing a wildcard identifier. I think this was discussed before and I see it as fairly unlikely, I think folks will balk at this.

I'll try to submit a PR and start a mailing list thread about this shortly. Thanks for the reminder!

**Comment by fszlin** [comment]
Thanks for the help and clarification. The [API doc](https://github.com/fszlin/certes/blob/master/docs/APIv2.md) is updated to match implementation now.
