### ISSUE TITLE
Incompatible with PowerShell Core due to Newtonsoft.Json 11.0.1

### ISSUE THREAD

**Issue by NiknakSi** [fszlin/certes#112]
I'm unable to use the Certes library in PowerShell Core due to the dependency on NewtonSoft.Json 11.0.1. At present you will receive a type init exception as soon as you try to create a new AcmeContext. This is due to the unique way pwsh works where it will stick with the first version of a module it loads, and unfortunately since pwsh itself has a dependency on Newtonsoft.Json, it sticks with the version it loads on startup.

See here: https://github.com/PowerShell/PowerShell/issues/2083

Currently there is no way for a module to have its own AppDomain or context. Until the PowerShell team fix that (maybe in 6.2), please could you revert the version of Newtonsoft.Json used by Certes to 10.0.3? I've grabbed the repo, made the change, and it compiled ok. The referenced assembly then works ok in PowerShell Core.

**Comment by fszlin** [comment]
Hi @NiknakSi , I am not sure this is a proper solution, but it’s fine to me if this allows you to use Certes in PowerShell core.

Looks like you have the changes ready, feel free to send a pull request. :wink:
Does it require exactly 10.0.3? will 10.0.1 or 9.0.1 compatible?

**Comment by NiknakSi** [comment]
I agree it's not really a proper solution, but it's the only one I can see at the moment. Microsoft may add better isolation for imported modules and/or assembly redirects. PowerShell 5.1 is fine at the moment.

It does need to be exactly 10.0.3 since that's what PS Core is using. The Nuspec should be ok with >= 10.0.3 in it though.

I've setup a PR, #115 

Thanks :)
