### ISSUE TITLE
subject alt name when issuing a wildcard, is that possible?

### ISSUE THREAD

**Issue by frankhommers** [fszlin/certes#114]
I am requesting a wildcard certificate like so:
*.sub.example.com and that works.

When getting a wildcard certificate from a paid CA, I usually get a certificate which are valid for:
*.sub.example.com
sub.example.com

How do I do that?
Is that possible with certes? (Or LetsEncrypt even?)

**Comment by NiknakSi** [comment]
Absolutely! AcmeContext.NewOrder() accepts a string array of domains. You'll need to iterate through your IOrderContext.Authorizations (one per domain) and the DNS challenges and satisfy all of that (remember that your DNS TXT record can contain multiple values, i.e. _acme-challenge.sub.example.com would have a value for 'sub.example.com' and one for '*.sub.example.com'). Finally, your CSR needs to be done manually, a bit like this:

        var csrBuilder = new CertificationRequestBuilder();
        csrBuilder.AddName($"C=CA, ST=State, L=City, O=Dept, CN={domains.First()}");

        if (domains.Count() > 1)
            csrBuilder.SubjectAlternativeNames = domains.Skip(1).ToList();

        byte[] csr = csrBuilder.Generate();
        await _OrderContext.Finalize(csr);

I've got all of this working in a little library I wrote that uses Certes: https://twitter.com/SimonHoade/status/1001115956578521088

**Comment by frankhommers** [comment]
Thanks guys! I can work with this. @NiknakSi: Is your code open source as well? :-)

**Comment by NiknakSi** [comment]
@frankhommers It definitely will be but not for a couple of weeks, it's a bit too incomplete at the moment!!

**Comment by NiknakSi** [comment]
@frankhommers I just published my code so far, it may be of use to you? See: https://github.com/NiknakSi/Certiply

**Comment by webprofusion-chrisc** [comment]
@NiknakSi Certiply huh? Snappy name 👍

**Comment by webprofusion-chrisc** [comment]
On a tangent, I've noticed the Certes example code sets Distinguished Name and City etc, but as far as I know those are all unsupported for Let's Encrypt certs and will be discarded? Only Common Name and SAN fields get populated as far as I can see.

**Comment by NiknakSi** [comment]
@webprofusion-chrisc That's true, only CN and SAN are used right now. I've kept the ability to specify the other values in my project just in case LE support it some day.
