### ISSUE TITLE
How do I generate a SAN certificate

### ISSUE THREAD

**Issue by guillaumeraymond** [fszlin/certes#12]
Hi, 
I'm trying to generate a SAN certificate. The SubjectAlternativeName property is readonly (and returns an empty list of string by default).

any attempt to add a name of type "DNS" fails since there is a validation on "X509Name.DefaultLookup" and the DNS is part of the X509Name.Extension
Any help would be appreciated

Thanks !

**Comment by fszlin** [comment]
You probably already figured out :wink:

```C#

var csr = new CertificationRequestBuilder();
csr.AddName("CN=CA, ST=Ontario, L=Toronto, O=Certes, OU=Dev, CN=www.certes-ci.dymetis.com");
csr.SubjectAlternativeNames.Add("mail.certes-ci.dymetis.com");
csr.SubjectAlternativeNames.Add("sso.certes-ci.dymetis.com");

await client.NewCertificate(csr);

```
