### ISSUE TITLE
KeyAlgorithm : 

### ISSUE THREAD

**Issue by davidverriere** [fszlin/certes#127]
When I want to use KeyAlgorithm.ES512 like that 

```
                var privateKey = KeyFactory.NewKey(KeyAlgorithm.ES512);
                var cert = await orderContext.Generate(new CsrInfo
                {
                    CountryName = certificateInfo.CountryName,
```

A 400 bad request is returned : 
```
{
  "type": "urn:ietf:params:acme:error:malformed",
  "detail": "Error finalizing order :: invalid public key in CSR: ECDSA curve P-521 not allowed",
  "status": 400
}
```

Only RS256 works but this algorithm is too weak.

Anybody is able to use a stronger algorithm ?
thanks

**Comment by fszlin** [comment]
Hi @davidverriere , this is controlled by LE.
Locking at [boulder's check for CSR key](https://github.com/letsencrypt/boulder/blob/6fe950bc0c777f04dd433a3dbded888fdd032fa5/goodkey/good_key.go#L184-L195), I believe ES384 would work.

**Comment by davidverriere** [comment]
Thanks for your answer.
Indeed ES384 works.
