### ISSUE TITLE
Wildcard SAN authorizations

### ISSUE THREAD

**Issue by elizabeth-young** [fszlin/certes#131]
I'm creating a wildcard certificate with 100 SANs and noticed that the authorizations returned from:

`await order.Authorizations();`

don't contain an identifier for the authorization.

Please can you tell me if the order of the authorizations will be the same as the order of SANs

Many thanks
Elizabeth Young

**Comment by fszlin** [comment]
Hi @elizabeth-young , I believe it should contain all identifiers from the order.

Could you check if `(await order.Resource()).Identifiers` has all the identifiers?

**Comment by elizabeth-young** [comment]
Hi @fszlin,

It does thanks, your comment also led me to `(await authz.Resource()).Identifier`  which I can use in my loop.

Many thanks :-)
