### ISSUE TITLE
PFX missing private key when importing into IIS

### ISSUE THREAD

**Issue by TraGicCode** [fszlin/certes#138]
I went through the whole process of creating a certificate and when i try and export it VIA PFX and the import it into IIS i get the following error.  What am i doing wrong?

![image](https://user-images.githubusercontent.com/6224270/42448287-63367f8c-8342-11e8-9199-c4dd56e66ee2.png)

**Comment by TraGicCode** [comment]
I found this issue.  It looks like the CLI allows you to output a PFX when telling it to generate a PEM which is not a valid CLI argument combination.  

```
certes.exe cert pem $order.location 123123 --private-key ./key.pem --out cert.pfx
```

I would classify this as a bug.  Let me know if you need anymore information!

**Comment by fszlin** [comment]
looks like the bug is in document. For PFX, it should be `certes cert pfx`.
