### ISSUE TITLE
Challenges and Limits

### ISSUE THREAD

**Issue by AeonDave** [fszlin/certes#140]
Hello!
after ordering some certificates i encountered some problems:

i have many subdomains so i have to issue many orders like this
```
var order1 = await acme.NewOrder(new[] { "a.domain.name","*.a.domain.name" });
var order2 = await acme.NewOrder(new[] { "b.domain.name","*.b.domain.name" });
var ordern = await acme.NewOrder(new[] { "n.domain.name","*.n.domain.name" });
```

in the docu the example code for challenges is:
`var authz = (await order.Authorizations()).First();`

why i have to take only the first?
i noticed that sometimes the validating process fail because some challenges are still in pending state.
so in my code i keep tracks of all the challenges and i try to validate all

```
var l = new HashSet<IChallengeContext>();
            var authz = await order.Authorizations();
            foreach (var a in authz)
                l.Add(await a.Dns());
            return l;
```
Is my approach correct?
of course i reach "Certificates per Registered Domain" limit very fast.
wildcards like *.*.domain.name are not allowed. how i can overcome to this issue?

Thanks

D

**Comment by fszlin** [comment]
It looks like you can use `*.domain.name` to cover `a.domain.name`, `b.domain.name`...?
I'd create an order for `*.domain.name`, `*.a.domain.name`, `*.b.domain.name`....`*.n.domain.name`.

> If you have a lot of subdomains, you may want to combine them into a single certificate, up to a limit of 100 Names per Certificate. Combined with the above limit, that means you can issue certificates containing up to 2,000 unique subdomains per week. A certificate with multiple names is often called a SAN certificate, or sometimes a UCC certificate.

**Comment by AeonDave** [comment]
ok sounds legit. with ofc the 2000 record limits

last thing..

> in the docu the example code for challenges is:
> var authz = (await order.Authorizations()).First();
> 
> why i have to take only the first?
thank you!

**Comment by fszlin** [comment]
That's because the example has only 1 domain in the order, so it should has only 1 authorization.
I guess `foreach` is better here?
