### ISSUE TITLE
Alternative CA cert management

### ISSUE THREAD

**Issue by pkiguy** [fszlin/certes#144]
Following to #142 and #143 , what about trying this:
[getCAFromWindowsStore.diff.txt](https://github.com/fszlin/certes/files/2192642/getCAFromWindowsStore.diff.txt)

Note: this code is completely untested.

**Comment by fszlin** [comment]
It looks great. Any idea for implement similar function on non-windows?

**Comment by pkiguy** [comment]
unfortunately no... on MacOS there's the keychain, but i don't know how it's interfaced with .NET. And on Linux, at best there's a directory with CA certs, but the directory location varies from one distribution to another.
So i guess the code i submitted should be within #ifdef _Win32 if you want to keep compatibility with other systems.
