### ISSUE TITLE
Set friendly name on pfx files with certes-cli

### ISSUE THREAD

**Issue by Tasteful** [fszlin/certes#145]
When you have a lot of different certificates that is generated with certes it is hard in the IIS manager to distinguish them and pick the correct one.
![image](https://user-images.githubusercontent.com/357589/42882074-c29f3a10-8a98-11e8-978a-59f8a6cf0648.png)

If we can add an additional `--friendly-name` parameter when we generate the PFX we can make it more user friendly to find correct certificate.
![image](https://user-images.githubusercontent.com/357589/42882198-ea71703a-8a98-11e8-9e65-e946418c0317.png)

If you think this is a good feature for everyone I'm happy to contribute with an PR from https://github.com/Tasteful/certes/tree/friendly-name

**Comment by fszlin** [comment]
It looks great to me, please send the PR.

**Comment by fszlin** [comment]
Deployed as v1.0.3, thanks.
