### ISSUE TITLE
Strange issue

### ISSUE THREAD

**Issue by batooo** [fszlin/certes#15]
I noticed my service is not working last 24 hours or maybe last few days. Once debugging locally, I noticed that Certes is stucking without error or timeout. I tried 1.1.0, 1.0.7 and also reverting to 1.06 but no luck.

Certes is stucking in my projects as MVC, but it's working fine in a Console app.
Visual Studio:

1. Create .NET 4.5 Console + Certes nugget = work
2. Create .NET 4.5 Web/MVC+ Certes nugget = stuck

Fiddler debugger shows how Certes is getting HTTP response for /directory and stucking after that.

`
GET https://acme-staging.api.letsencrypt.org/directory HTTP/1.1
Host: acme-staging.api.letsencrypt.org
Connection: Keep-Alive

HTTP/1.1 200 OK
Server: nginx
Content-Type: application/json
Content-Length: 581
Boulder-Request-Id: ZC8.....
Replay-Nonce: hEfFm......
X-Frame-Options: DENY
Strict-Transport-Security: max-age=604800
Expires: Sun, 20 Aug 2017 23:50:00 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Sun, 20 Aug 2017 23:50:00 GMT
Connection: keep-alive

{
  "V6lWPRqlCVw": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "key-change": "https://acme-staging.api.letsencrypt.org/acme/key-change",
  "meta": {
    "terms-of-service": "https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf"
  },
  "new-authz": "https://acme-staging.api.letsencrypt.org/acme/new-authz",
  "new-cert": "https://acme-staging.api.letsencrypt.org/acme/new-cert",
  "new-reg": "https://acme-staging.api.letsencrypt.org/acme/new-reg",
  "revoke-cert": "https://acme-staging.api.letsencrypt.org/acme/revoke-cert"
}
`
Do i miss something?

**Comment by batooo** [comment]
Sorry, this is due to HTTP client async issue. My mistake.

**Comment by snepgoyal** [comment]
Hi Batooo I am facing the same problem. How did u solved your problem?
