### ISSUE TITLE
How to correlate domains to http challenges?

### ISSUE THREAD

**Issue by Haukinger** [fszlin/certes#152]
When issuing an order for multiple domains I get multiple authorization contexts from `IOrderContext.Authorize`, each of which produces an http challenge (by calling `Http`).

How do I know which challenge to upload to which domain?

**Comment by KenHundley** [comment]
You can look at the resource identifier on the authorization
```csharp
var order = await acme.NewOrder(domains);
var authorizations = await order.Authorizations();
foreach (var authorization in authorizations)
{
    var resource = await authorization.Resource();
    var domain = resource.Identifier.Value; // << This has the domain for the validation
}
```

**Comment by Haukinger** [comment]
Works perfectly fine, thinks a lot!
