### ISSUE TITLE
Update Certificate

### ISSUE THREAD

**Issue by waltergrimmvie** [fszlin/certes#157]
HI,

Getting cert is working fine, I am looking on how to update the cert now, other LE tools have the update option, which I am completly missing, can anyone help me with this please.

thanxs

**Comment by webprofusion-chrisc** [comment]
@waltergrimmvie when you need to renew a certificate you actually create a whole new request (an update is just re-issuing the same request). Let's Encrypt will recognise it is a request for a new version of the same certificate for the same account (based on your account id and the list of domains in the certificate).

**Comment by waltergrimmvie** [comment]
Thanx for the quick response,
