### ISSUE TITLE
Certes should not use System.Net.Http NuGet for desktop frameworks

### ISSUE THREAD

**Issue by Danielku15** [fszlin/certes#158]
Currently Certes is pulling System.Net.Http via NuGet. But this should be avoided for the Desktop Frameworks (net45, net47). 

![image](https://user-images.githubusercontent.com/674916/46812520-29be3880-cd75-11e8-9314-ae9d01fd7b52.png)

Most frameworks and libraries on desktop rely on the System.Net.Http that comes with the normal desktop .net Framework installation. Pulling the System.Net.Http NuGet causes typically a DLL-hell even though it should not result in additional DLLs added. Something gets messed up with version numbers and assembly redirects. 

https://github.com/fszlin/certes/blob/eedf1a1fefd578c705d6dc82cc5ca81986b77ee6/src/Certes/Certes.csproj#L41

The code above should be replaced by 
```xml
<Reference Include="System.Net.Http" Condition="'$(TargetFramework)' == 'net45' Or '$(TargetFramework)' == 'net47'" />
```

Here some similar issues from other projects

https://github.com/IdentityModel/IdentityModel2/issues/76
https://github.com/dotnet/corefx/issues/29622
https://github.com/serilog/serilog-sinks-splunk/issues/77
https://github.com/Azure/Azure-Functions/issues/477

**Comment by fszlin** [comment]
Thanks, will make the changes.

**Comment by Danielku15** [comment]
Thanks a lot for the quick change. Do you already have an idea when you will publish this change to NuGet?

**Comment by fszlin** [comment]
Should be live on [Nuget](https://www.nuget.org/packages/Certes/2.3.1) now. Sorry for the delay.

**Comment by Danielku15** [comment]
Thanks a lot. I will directly attempt to upgrade our projects.
