### ISSUE TITLE
Challenge cannot be fulfilled on staging

### ISSUE THREAD

**Issue by PovilasVytautasC** [fszlin/certes#16]
Recently I noticed that trying to issue a certificate on LE staging environment no longer works. After an investigation I've noticed that calls are never made to the domain to check for the challenge. Undergoing the same procedure but using LE production environment works fine.

The domain I tried to issue a certificate to was buduls.tk,

**Comment by cpu** [comment]
>  Recently I noticed that trying to issue a certificate on LE staging environment no longer works.

There has been [an ongoing disruption to the staging environment](https://community.letsencrypt.org/t/staging-disruption/40582) today/last night. I believe this problem is related. It should be resolved shortly.
