### ISSUE TITLE
Account re-use example?

### ISSUE THREAD

**Issue by esw0000000** [fszlin/certes#17]
Could you give an example of how to request a certificate using an existing account (rather than creating a new one)?

**Comment by fszlin** [comment]
If you have your account key in DER, you may load it in to `AcmeClient`

``` C#
using (var client = new AcmeClient(WellKnownServers.LetsEncrypt))
{
    var key = new KeyInfo { PrivateKeyInfo = Convert.FromBase64String("MIIEvgIBA...kmMx9v") };
    client.Use(key);

    // ...
 }
```

Check this [test](https://github.com/fszlin/certes/blob/8707cdff3c9212d51229d7f9ec8093d2945320a8/test/Certes.Tests/AcmeClientTests.cs#L64), which is reusing the account key.

**Comment by esw0000000** [comment]
Thank you!

**Comment by fszlin** [comment]
You are welcome. 
close #17
