### ISSUE TITLE
Can't create new account on live

### ISSUE THREAD

**Issue by ianadavies** [fszlin/certes#172]
I have this very simple code

```
var acmeContext = new AcmeContext(WellKnownServers.LetsEncryptV2);
await acmeContext.NewAccount(certesAcmeAccountConfiguration.AccountName, true);

```

And it's failing with

 

> An ACME Exception Occured
> Certes.AcmeRequestException: Fail to load resource from 'https://acme-v02.api.letsencrypt.org/acme/new-acct'.
> urn:ietf:params:acme:error:malformed: Error unmarshaling JSON
>    at Certes.Acme.IAcmeHttpClientExtensions.Post[T](IAcmeHttpClient client, Uri uri, Object payload, Boolean ensureSuccessStatusCode)
>    at Certes.Acme.AccountContext.NewAccount(IAcmeContext context, Account body, Boolean ensureSuccessStatusCode)
>    at Certes.AcmeContext.NewAccount(IList`1 contact, Boolean termsOfServiceAgreed)

Any Ideas what i'm doing wrong ?

**Comment by webprofusion-chrisc** [comment]
Hi,
Is `certesAcmeAccountConfiguration.AccountName` a list?

https://github.com/fszlin/certes/blob/master/src/Certes/AcmeContext.cs#L111

My only guess would be that the email address provided in the AccountName string list is empty or invalid somehow?

**Comment by ianadavies** [comment]
I don't think so, The email was definitely there and in the end I ended up creating the account with certbot which worked fine (the same email address I was trying with certes) Also would really like to know why certes masks all the errors from lets encrypt it's really not helpful as I can't see what the real issues are.
