### ISSUE TITLE
Feature request: Non-async api

### ISSUE THREAD

**Issue by osjoberg** [fszlin/certes#179]
Great work, easy to use - got everything working very quickly given the minimal examples, even though I had to fumble around until I realized how to do the validation call properly.

This is not a critique but just some feedback:

My context is not an async context (it is in a C# script). I see async as an optimization for scalability which is not important for me (and may not be for many others as well). Calling async methods when you are not in an async context is akward, therefore I expect most APIs to both have "regular" methods and "async" methods so that the developer can choose to use more scalable primitives only when needed.  

I realize that this may be a breaking change so it might not be too easy to change now, but maybe for the future?

**Comment by webprofusion-chrisc** [comment]
@osjoberg this is probably unlikely to happen unless you submit a PR :) - many of the operations the library performs are async in nature (indeterminate http calls back to the ACME CA for instance), so the API is just following that in a conventional kind of way. Additionally the Async methods are not Suffixed as Async in the name so everything would need renamed (or moved to a different namespace).

Which c# scripting environment are you using? Presumably they allow you to start an async context there?

**Comment by osjoberg** [comment]
I am working with LinqPad. Now when I googled this I realize I sure can write async scripts in LinqPad.

However my main gripe still remains, being forced to use Async when there is no need to do an optimization makes my code more complicated. Also it pollutes the code so that I need to run async all the way up to all call sites above the code calling the Certes API unless I take extra steps to wrap the code so that it no longer Async.  

Having one blocking thread even for long http calls is not an issue as there are no other threads running in this process.

However, as I do realize it is impossible to solve this without breaking the API, this is more for if there ever is a redesign that will need to break the API anyways.

**Comment by TachyonRSA** [comment]
@osjoberg - Can you possibly have a look at #180 and share your validation call please?
