### ISSUE TITLE
Order's status ("pending") is not acceptable for finalization

### ISSUE THREAD

**Issue by TachyonRSA** [fszlin/certes#180]
I am currently trying to generate a certificate for my domain but keep running into the error as follows:

> Fail to load resource from 'https://acme-staging-v02.api.letsencrypt.org/acme/finalize/8478299/25683101'.
> urn:ietf:params:acme:error:orderNotReady: Order's status ("pending") is not acceptable for finalization

This is after checking that the `dnsChallenge.Validate()` result is `ChallengeStatus.Valid`. I don't understand how the `Validate()` method can return valid but yet I am running into an error where the order status is pending.

**Comment by osjoberg** [comment]
I don't think you are doing the same error as I did. 

Are you trying to make an order for multiple domains? In that case it would make sense that you only have note validated all challenges?

**Comment by TachyonRSA** [comment]
I am making an order for a wildcard and then the domain itself, i.e. `*.test.com` and `test.com`, surely that is only one DNS challenge?

**Comment by osjoberg** [comment]
I have not done DNS challenge myself so I dont know, check if  the result of await order.Authorizations() have more than one element.

**Comment by cpu** [comment]
>  surely that is only one DNS challenge?

It would be two TXT records under the same `_acme-challenge.<domain>` label.

**Comment by TachyonRSA** [comment]
> > surely that is only one DNS challenge?
> 
> It would be two TXT records under the same `_acme-challenge.<domain>` label. Two authorizations, two DNS-01 challenges. See [letsencrypt/boulder#4094](https://github.com/letsencrypt/boulder/issues/4094) for more background.

Okay that makes sense, thank you very much. I will update my code accordingly.
