### ISSUE TITLE
Compatibility with .NET Framework v4.5

### ISSUE THREAD

**Issue by aloopkin** [fszlin/certes#183]
Hello,

It seems that the version available in nuget isn't really compliant with .NET Framework 4.5. When trying to load it on a bare .NET Framework 4.5, it fails with error:
`Could not load file or assembly 'System.Net.Http, Version=4.1.1.3, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.`

Maybe i'm doing something wrong, but the standalone System.Net.Http lib available in nuget has dependencies that work only on .NET Framework 4.6+, and the one embedded in .NET Framework 4.5 indeed has a lower version number.

Can you help, please?

**Comment by webprofusion-chrisc** [comment]
Hi, when you add the System.Net.Http nuget to your project you should be able to need to add version 4.1.x (4.1.4?)  which has no extra dependencies on .net 4.5, instead of using the latest version. You may need a binding redirect or use auto binding redirects.

**Comment by aloopkin** [comment]
Actually, it seems that restarting from a clean project environment solved the issue. Seems that nuget simply didn't figure out correctly how to use the System.Net.Http included in dotNet framework.
