### ISSUE TITLE
Cannot finalize order with status 'Invalid'

### ISSUE THREAD

**Issue by jfalameda** [fszlin/certes#186]
Hi,

I am trying to generate a certificate using DNS authorization. I have checked multiple times the validity of the TXT record and even waited large amounts of time before verifying the challenge. I always get the same error, which is hard to understand the underlying cause for that error.

An exception `Cannot finalize order with status 'Invalid'` is thrown when calling `order.Generate`

Could be that there is something wrong on my side, but as far as I can see I am following the examples outlined on the documentation.

This is how my code looks like:
```c#
var acme = new AcmeContext(WellKnownServers.LetsEncryptStagingV2);
var account = await acme.NewAccount("xxx@xyz.se", true);

// Save the account key for later use
var pemKey = acme.AccountKey.ToPem();

var order = await acme.NewOrder(new[] { "*.xyz.se" });

var authz = (await order.Authorizations()).First();
var dnsChallenge = await authz.Dns();
var dnsTxt = acme.AccountKey.DnsTxt(dnsChallenge.Token);

LoopiaRPCCalls.createTxtRecord(dnsTxt);

// At this point _acme-challenge.xyz.se is created

Thread.Sleep(60 * 1000);

await dnsChallenge.Validate();

var privateKey = KeyFactory.NewKey(KeyAlgorithm.ES256);

var cert = await order.Generate(new CsrInfo // At this point an exeption is thrown
{
    CountryName = "SE",
    State = "Stockholm",
    Locality = "Stockholm",
    Organization = "XYZ",
}, privateKey);

var pfxBuilder = cert.ToPfx(privateKey);
var pfx = pfxBuilder.Build("xyz", "");
```

Thanks in advance.

**Comment by jfalameda** [comment]
I realized this is caused by the TTL on the TXT record. The DNS service was most likely providing a cached version to let's encrypt.

This ticket can be closed.

**Comment by jshepler** [comment]
What I've done in the past is write code to loop doing DNS lookups until the correct TXT value is returned. Waiting for X minutes isn't reliable.
