### ISSUE TITLE
API docs on exporting certificate to pfx incorrectly references CertificateInfo

### ISSUE THREAD

**Issue by jshepler** [fszlin/certes#187]
https://github.com/fszlin/certes/blob/master/docs/APIv2.md#certificates

The section on exporting to PEM, DER, or PFX  has this line
`var cert = new CertificateInfo(certChain, certKey);`

I don't think CertificateInfo exists.

**Comment by eydelrivero** [comment]
Hi, 
Any comments on this? I'm also trying to follow that same piece of documentation.

**Comment by DMF84** [comment]
Seriously! What should we do with this problem? It is already the middle of 2020, and there is still no answer...

**Comment by esw0000000** [comment]
Here's working code from my app (hope this helps):

`var privateKey = KeyFactory.NewKey(KeyAlgorithm.ES256);`
`var cc = await order.Generate(
                                new CsrInfo
                                {
                                    CountryName = "US",
                                    State = "State",
                                    Locality = "City",
                                    Organization = "Org",
                                }, privateKey);`
`var pfx = cc.ToPfx(privateKey);`
