### ISSUE TITLE
Unable To Export Pfx/X509Certificate2 With Private Key Exportable

### ISSUE THREAD

**Issue by andrejohansson** [fszlin/certes#190]
I have been twisting my head around this now for a while. I am unable to get an valid X509Certificate2 instance with an **exportable private key** using Certes.

Here is my code (taken from the documentation pretty much) so far:

```csharp
var csrInfo = new CsrInfo
{
    CountryName = _certificateInfo.CountryName,
    State = _certificateInfo.State,
    Locality = _certificateInfo.Locality,
    Organization = _certificateInfo.Organization,
    OrganizationUnit = _certificateInfo.OrganizationUnit
};

var privateKey = KeyFactory.NewKey(KeyAlgorithm.ES384);
var certChain = await order.Generate(csrInfo, privateKey).ConfigureAwait(false);

var pfxBuilder = certChain.ToPfx(privateKey);

var password = Password.Generate(32, 12);
var pfxBytes = pfxBuilder.Build(domain, password);

// Exception here! Certificate.HasPrivateKey = true but its marked non exportablem could it be the reason?
// System.PlatformNotSupportedException : Operation is not supported on this platform.
var certificate = new X509Certificate2(pfxBytes, password, X509KeyStorageFlags.Exportable);
var pk = certificate.PrivateKey.ToXmlString(true);

return (certificate, password);`
```

The first part will return an instance of ``X509Certificate2`` with the property ``HasPrivateKey=true`` however I am unable to use it since its marked not exportable.

I am trying to use the resulting certificate in an Azure App service arm template deployment by uploading the certificate to keyvault and referencing it in the template. But whenever I use a certificate generated using the above code, I get an ``BadRequest`` error with message ``The parameter KeyVault Certificate has an invalid value.`` and I suspect it is because the private key is marked as not exportable. 

If I generate a letsencrypt certificate using the le64 utility and put in the keyvault, everything works as expected.

Any idea what could be wrong here?

**Comment by ericwj** [comment]
The presence and exportability of `X509Certificate2` depends on the ability of the .NET Framework of doing just that by essentially calling into P/Invoke. .NET Core isn't as complete as full framework. You could try to run this code on full framework and verify that it does not throw `PlatformNotSupportedException` assuming you are using .NET Core to run the above code.

However, even if full framework also throws, you don't have to go through `X509Certificate2`. Your `pfxBytes` array contains all the bytes you need and you can use those with KeyVault. So even just doing `File.WriteAllBytes(filename, pfxBytes)` and use the pfx file instead will also work quite allright.

**Comment by webprofusion-chrisc** [comment]
If still having trouble with private key storage try this set of flags:
```cs
X509KeyStorageFlags.MachineKeySet | X509KeyStorageFlags.PersistKeySet | X509KeyStorageFlags.Exportable
```

Closing this is issue as it's not specific to the certes library or cli.
