### ISSUE TITLE
How to retreive existing challenge details?

### ISSUE THREAD

**Issue by Jagjit-enest** [fszlin/certes#193]
Hi Team,

We are offering custom domains with SSL in our system and we want to use the DNS method for validation.

1) We are capturing domain from our users via an interface.
2) After getting domain we are placing SSL order with let's encrypt and we are returning the TXT details to user so that they can put in their DNS server and we are saving the challenge URI, token and other things in db that means we are delaying the validation process here.
3) After they confirm that they have entered the TXT records on their DNS server. We want to retrieve the challenge details from the token and challenge URI so that we can initiate the validation process

I tried the below but still getting nothing. Can anyone can help me here to do that.

                var pemKey = "<mykey here>";

                var keytDetails = KeyFactory.FromPem(pemKey);

                var accountPemKey = keytDetails.ToPem();

                var acme = new AcmeContext(WellKnownServers.LetsEncryptV2, keytDetails);

                var url = @"https://acme-v02.api.letsencrypt.org/acme/challenge/eswXZ2EfrXlpg5UDyooHs7qm_z3i1dWPZ19uWwSJGNk/18335479490";

                var uri = new Uri(url);

                var authoDet = acme.Authorization(uri);

                var challenges = await authoDet.Challenges();

**Comment by Jagjit-enest** [comment]
@fszlin  Can you please check this issue for me.

**Comment by sanja8686** [comment]
This is not an issue... here is the solution of your problem,

```c#
List<IAuthorizationContext> authzs = challenges.ToList();
for (int i = 0; i < authzs.Count; i++)
{
//this is the detail of particular challenge detail
Certes.Acme.Resource.Authorization authdetail = await authzs[i].Resource();
}
```
