### ISSUE TITLE
Issue while using other domain name than "www.certes-ci.dymetis.com".

### ISSUE THREAD

**Issue by gititmsc** [fszlin/certes#195]
:beer: Feel **free** to discuss anything :beer:
I am trying to generate certificate but it throws error like "Can not finalize order with status 'Invalid'."What can be an issue?please guide

**Comment by webprofusion-chrisc** [comment]
When you create the certificate order, you then have to validate by proving you control the domain either using http validation or dns validation. If your order is invalid it likely failed validation (your http or dns validation response was wrong).

Let's Debug is useful for diagnosing issues: https://letsdebug.net/
