### ISSUE TITLE
Switch in Challenge types results in validation forever 'pending' state

### ISSUE THREAD

**Issue by anilripla** [fszlin/certes#196]
1. I validated a domain (shopeneur.com) with the DNS-01 challenge type and it was successful
2. When I try to switch the validation for the same domain (shopeneur.com) and validate with HTTP-01, the HTTP-01 validation is stuck on 'pending' forever. 

The first time the domain is validated, the overall status is set to valid. The DNS-01 challenge is returned as 'valid' and the HTTP-01 is returned as 'pending'. 

Since the overall status is 'valid', the ACME API does not bother to run the HTTP-01 challenge on subsequent validation requests and its stays 'pending' forever.

Is there is fix for this?

```{
  "identifier": {
    "type": "dns",
    "value": "shopeneur.com"
  },
  "status": "valid",
  "expires": "2019-09-28T00:48:42Z",
  "challenges": [
    {
      "type": "http-01",
      "status": "pending",
      "url": "https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/5236853/tFVOlw",
      "token": "_Y3QVaazw5T8hAaZBRCCjPH7K0XzYh85BqmtBp3NbxE"
    },
    {
      "type": "dns-01",
      "status": "valid",
      "url": "https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/5236853/X72ZQg",
      "token": "_Y3QVaazw5T8hAaZBRCCjPH7K0XzYh85BqmtBp3NbxE",
      "validationRecord": [
        {
          "hostname": "shopeneur.com"
        }
      ]
    },
    {
      "type": "tls-alpn-01",
      "status": "pending",
      "url": "https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/5236853/ZH7HXQ",
      "token": "_Y3QVaazw5T8hAaZBRCCjPH7K0XzYh85BqmtBp3NbxE"
    }
  ]
}

**Comment by webprofusion-chrisc** [comment]
Since you have validated using DNS you do not have to attempt http validation. You can now proceed to request your certificate. Alternatively you can start a new order to begin validation again.

**Comment by webprofusion-chrisc** [comment]
Ah, I forgot that validation is cached by Let's Encrypt for about 30 days, so yes you will stay validated until that expires.

**Comment by webprofusion-chrisc** [comment]
You could possibly start a new account key.
