### ISSUE TITLE
`context.NewAccount` never returns

### ISSUE THREAD

**Issue by fcallejon-flipdish** [fszlin/certes#197]
Hi, 

I have been trying to create an account doing:

```
            _acmeContext = new AcmeContext(WellKnownServers.LetsEncryptStagingV2, http: _acmeHttpClient);
            try
            {
                var account = await _acmeContext.NewAccount(new List<string> { _leAccountEmail }, true);
                return _acmeContext;
            }
            catch
            {
               // just to check if there is an exception
                throw;
            }
```
But the task started by NewAccount are just awaiting:
![image](https://user-images.githubusercontent.com/54269575/63874652-d3bca880-c9b9-11e9-8239-bf42b14b49ea.png)

I've also tried using the extension method were you only pass an email address.
Doing `GetAwaiter().GetResult()`, using prod, using v1 (both). Always the same result: the task just hangs in there.

**Comment by webprofusion-chrisc** [comment]
Hi, that's odd! Try firing up Fiddler and see if the https request to the staging API is being made and getting a response. I assume your machine can make outgoing https requests no problem.

**Comment by webprofusion-chrisc** [comment]
Also try just using the `.NewAccount(email, true)` overload of that method, I haven't tried the list version.

**Comment by fcallejon-flipdish** [comment]
Hi, I've tried both methods.

I'll check fiddler and post the result.

**Comment by fcallejon-flipdish** [comment]
Here is the fiddlers session with the two only calls, the calls seems to come back fine.

[Certes.Fiddler.txt](https://github.com/fszlin/certes/files/3554522/Certes.Fiddler.txt)

**Comment by fcallejon-flipdish** [comment]
Hi,

maybe I forgot to say that I;m using it from a ASP.Net Controller.
I did some changes to the src and added a few ConfigureAwait(false) and it kind of fixed it, but there are still some deadlocks because of the sync context.

Anyway you may want to add ConfigureAwait(false) to the HttpClient calls.

**Comment by fcallejon-flipdish** [comment]
Solved it by adding a few ConfigureAwait(false) on my code.
