### ISSUE TITLE
Registration guidance

### ISSUE THREAD

**Issue by KenHundley** [fszlin/certes#20]
Hi, 
I've got a custom implementation of Certes working using the Nuget package, however, I'm not sure how to handle the registrations. Is it appropriate and expected that I call `client.NewRegistraton("mailto:myemail@example.com")` each time I run the application, or is there a mechanism that allows you to reuse previous registrations?

**Comment by fszlin** [comment]
Once you get the account object form ```client.NewRegistraton```, you can save ```account.Key``` and reuse it later.
See #17 to reusing the account key.

**Comment by KenHundley** [comment]
Ah, ty, 
Sorry for the duplicate question
