### ISSUE TITLE
Please add User-Agent header

### ISSUE THREAD

**Issue by jsha** [fszlin/certes#203]
Hi,

I'm an engineer at Let's Encrypt. We rely on User-Agent headers from ACME clients to figure out unusual access patterns. Lately I've seen a number of clients in our logs with no User-Agent header. After email a few of the owners, I've found that at least some of those people are using Certes. Could you please add a User-Agent header identifying Certes? Here's what RFC 8555 has to say on the topic:

```
ACME clients MUST send a User-Agent header field, in accordance with
[RFC7231]. This header field SHOULD include the name and version of
the ACME software in addition to the name and version of the
underlying HTTP client software.
```

**Comment by aloopkin** [comment]
Additionnally, can you please give the ability to add a string to the Certes user agent, so that we can distinguish between Certes-based clients.

**Comment by natemcmaster** [comment]
@fszlin - I use this project in my own tools, so thought I would help out here by providing a fix. Here's a pull request that adds the user-agent string to usages of HttpClient: https://github.com/fszlin/certes/pull/204

**Comment by jsha** [comment]
Hi @fszlin,

Do you think you'll have the ability to work on this soon?

Thanks,
Jacob

**Comment by natemcmaster** [comment]
The maintainer of this repo appears to be MIA. Maybe time to fork?
