### ISSUE TITLE
Add Support for keysize > 2048

### ISSUE THREAD

**Issue by areis422** [fszlin/certes#225]
Please include support for generating RSA keys > 2048 bits (Windows supports up to 16384 size keys in the Crypto provider). Also see what's available for ECC generation.

**Comment by areis422** [comment]
Bump to keep open

**Comment by areis422** [comment]
Bump

**Comment by jantytgat** [comment]
Is there any update on this? @fszlin @webprofusion-chrisc 
Is there a way I can contribute perhaps?

**Comment by webprofusion-chrisc** [comment]
@jantytgat thanks, this hasn't become a priority for me such that I need to fix it. Carefully put together pull requests with tests covered the modified functionality are accepted though :)

I started on this a while back but didn't finish it: https://github.com/webprofusion-chrisc/certes/tree/key-strength it needs rebased against master first then it needs stuff added to ensure key sizes are valid (eg. LE only supports a couple of sizes) and it needs tests.

Currently there are no new nuget releases, so you have to build your own copy of the library.

**Comment by areis422** [comment]
Bump

**Comment by ColinRaaijmakers** [comment]
Any update on this one?

**Comment by webprofusion-chrisc** [comment]
I've created a PR for this: https://github.com/fszlin/certes/pull/268

Note that various ACME CAs support different sets of key specifications, the most commonly supported RSA key sizes are currently 2048 and 3072. This is not applicable to EC keys in the same way.

**Comment by BravoTango86** [comment]
In the interim, I've been generating keys using the following which seems to work:
`
var newPrivateKey = System.Security.Cryptography.RSA.Create(4096);
var cert = await order.Generate(new CsrInfo {
    ...
}, KeyFactory.FromDer(newPrivateKey.ExportPkcs8PrivateKey()));
`
