### ISSUE TITLE
Please create a step-by-step document

### ISSUE THREAD

**Issue by ccasalicchio** [fszlin/certes#229]
I have followed the instructions the best I could, but keep getting the response

```
'https://acme-staging-v02.api.letsencrypt.org/acme/finalize/15627030/148966400'.
urn:ietf:params:acme:error:orderNotReady: Order's status ("pending") is not acceptable for finalization'
```

which means that I'm doing something wrong. But I am not sure what is missing, since the documentation tends to skip steps.
Also tried following the documentation here https://github.com/fszlin/certes/blob/master/docs/APIv2.md but still had no luck.

I will really appreciate some help

**Comment by ufuktankiyak** [comment]
I am getting this error too. Can anyone write what we should do step by step? 
I really think there is a lack of documentation on these issues

**Comment by esw0000000** [comment]
You need to check the challenge status before you try to finalize. Here's an example:


```
Challenge challenge; 

// Check authorization status
int tryCount = 1;

do
{
// Wait for ACME server to validate the identifier
await Task.Delay(5000 * tryCount);
challenge = await httpChallenge2.Validate();
Console.WriteLine(challenge.Status);
}
while (challenge.Status == ChallengeStatus.Pending && ++tryCount <= 20);

if (challenge.Status != ChallengeStatus.Valid)
{
// Don't proceed, ACME can't validate 
break;
}

// Complete the order

```

**Comment by Greg-Obleshchuk** [comment]
This doesn't work too well as it throws a exception if the request is not pending.  How do we get the status instead of calling validate?

**Comment by webprofusion-chrisc** [comment]
Hi, you need to refetch the status of your challenge. 

In the example @esw0000000 example provided you could use `challenge = await httpChallenge2.Resource()` which internally is a request to refetch the challenge and it's status.  So you call `.Validate()` to start, then re-check with `.Resource()` - or I do anyway.
