### ISSUE TITLE
A specified logon session does not exist. It may already have been terminated. (Exception from HRESULT: 0x80070520)

### ISSUE THREAD

**Issue by unknownguy** [fszlin/certes#23]
When I try to bind the certificate I get the following error:
A specified logon session does not exist. It may already have been terminated. (Exception from HRESULT: 0x80070520)

After some research I best I could find is this:
https://social.msdn.microsoft.com/Forums/sqlserver/en-US/8b78f6ca-d4db-4de1-a642-6223aa0252e7/unable-to-bind-a-new-certificate-in-ssrs-2008-r2?forum=sqlreportingservices
 
Any  help would be greatly appreciated.

**Comment by fszlin** [comment]
Could you share the code or steps you used to generate the certificate?

**Comment by unknownguy** [comment]
Sure. This is the part when I create the certificate:

`var csr = new CertificationRequestBuilder();

            csr.AddName("CN", domains.First());
            foreach (var alternativeName in domains.Skip(1))
                csr.SubjectAlternativeNames.Add(alternativeName);
            
            var cert = await client.NewCertificate(csr);
            
            var friendlyName = domains.First();
            friendlyName = friendlyName.Replace('.', '-');

            var password = Membership.GeneratePassword(20, 4);
            
            // Export Pfx
            var pfxBuilder = cert.ToPfx();
            var pfx = pfxBuilder.Build(friendlyName, password);

            return new CertificatePfx
            {
                Domains = domains,
                Data = pfx,
                FriendlyName = friendlyName,
                Password = password
            };`

**Comment by unknownguy** [comment]
Sorry about closing the issue. It's been a long week with this issue.

**Comment by unknownguy** [comment]
Then I try to import the certificate on server:

```
var newCert = new X509Certificate2(pfx.Data, pfx.Password, X509KeyStorageFlags.PersistKeySet | X509KeyStorageFlags.Exportable);

            if (!newCert.Verify())
            {
                //throw new Exception("Certificate is not valid!");
            }

            using (var readWriteMyStore = new X509Store(StoreName.My, StoreLocation.CurrentUser))
            {
                readWriteMyStore.Open(OpenFlags.ReadWrite);
                readWriteMyStore.Add(newCert);
                readWriteMyStore.Close();
            }

            var serverManager = new ServerManager();
            
            var site = serverManager.Sites[0];
            var binding = site.Bindings.Add(":443:" + pfx.Domains.First(), newCert.GetCertHash(), "My");
            binding.SetAttributeValue("sslFlags", 1); //enables the SNI

            serverManager.CommitChanges();
```

**Comment by fszlin** [comment]
Have you try installing the pfx locally into MMC? Can you export it again with private key?
What happen if you bind the SSL manually?

**Comment by unknownguy** [comment]
I've imported the pfx using the password and worked fine. I created the biding manually and it worked fine. I exported it to another pfx with a different password if this is what you mean.

**Comment by unknownguy** [comment]
It might have been a settings issue when I was adding the biding. With this setting it works fine:

var newCert = new X509Certificate2(pfx.Data, pfx.Password, X509KeyStorageFlags.Exportable);

and also this:

var readWriteMyStore = new X509Store(StoreName.My, StoreLocation.CurrentUser)

Now it binds with no errors and it works fine.

**Comment by fszlin** [comment]
great, thanks for the update.
