### ISSUE TITLE
How to create challenge with an existing key?

### ISSUE THREAD

**Issue by oktatas-ntszki** [fszlin/certes#230]
Hi,

I am testing the solution. The issue is that between the order creation and validation some hours could take as per configuring the http or dnsChallenge values. But if the configuration is done, when I want to validate it, in the dnsChallenge object there is a different key therefore the validation fails with Invalid error message.

How can I tell to the acme server that it should validate the previously configured challenge key?

Thanks!
Gabor Varga

**Comment by webprofusion-chrisc** [comment]
Hi, with Let's Encryp (ACME) validation you need to start the order, fetch the challenges, complete one of the challenges (in this case the DNS change), then submit the challenge for validation, if that passes and you have completed a challenge for each of the domains on your certificate then you can go ahead and request your certificate. 

So you don't want to request your challenges again, you want to hold onto your order and complete the existing challenge.
