### ISSUE TITLE
Is RSA keys hardcoded to 2048 bits?

### ISSUE THREAD

**Issue by m-barthelemy** [fszlin/certes#24]
I couldn't find any option to specify a custom private key size.
Maybe I haven't looked hard enough and in that case I'm sorry for the noise.
I saw in certes/src/Certes/Crypto/RS256Algorithm.cs that `GenerateKey()` seems to have 2048 hardcoded.

Is there any plan to allow generating 3072 and 4096 bits keys?
Thanks!

**Comment by fszlin** [comment]
Hi @m-barthelemy, yes, the key size is hardcoded when generating RSA key. You should be able to import RSA key pair with different key size and use it for CSR.

It is indeed a good suggestion to support creating RSA with specific key size, just need to figure what the API would look like.

**Comment by areis422** [comment]
Bump
