### ISSUE TITLE
Project Status and Maintenance

### ISSUE THREAD

**Issue by webprofusion-chrisc** [fszlin/certes#240]
Hi @fszlin you'll have noticed some activity on the project recently regarding new pull requests. I appear to have basic permissions required to merge PRs (thanks!). 

Did you want me to look after the process of merging these new PRs? I'm pretty sure my standards regarding test coverage etc are _not_ as high as yours but some of these features are quite high priority and I'd rather get them merged (within reason) and deal with bugs rather than limit the flow of contributions or let the project go stale while I still have a dependency on it.

**If I don't hear anything I'll assume it's ok and just go ahead with helping organise PRs merge.** 

We also have the issue of how to publish new releases and subsequent updates to nuget packages? I realise you may not have time to do all that, but I probably do if you can share permissions.

**Comment by wiggisser** [comment]
@webprofusion-chrisc Thanks for taking the initiative! I really appreciate it and would love to have a new release with at least the alternate link relation. 

In the meantime I'm using my own fork because we want support older androids as long as possible.

**Comment by webprofusion-chrisc** [comment]
@wiggisser that's your alternate link relation PR merged now. Regarding Android I'd also recommend looking at using BuyPassGo or ZeroSSL for your certs, specifically because their root cert has long been trusted and is likely to work better than the upcoming newer LE root cert.
