### ISSUE TITLE
[help] im try to make authorization of  domain

### ISSUE THREAD

**Issue by garsia0** [fszlin/certes#241]
im try to get HttpChallenge but receive null on all challenge what missing

AcmeContext Acme;
            Task<IAccountContext> m_Account;
            if (File.Exists("Account.pem"))
            {
                var accountKey = KeyFactory.FromPem(File.ReadAllText("Account.pem"));
                Acme = new AcmeContext(WellKnownServers.LetsEncryptStagingV2, accountKey);
                m_Account = Acme.Account();
            }
            else
            {
                Acme = new AcmeContext(WellKnownServers.LetsEncryptStagingV2);
                m_Account = Acme.NewAccount("email@gmail.com", true);
                // Save the account key for later use
                string pemKey = Acme.AccountKey.ToPem();
                File.WriteAllText("Account.pem", pemKey);
            }

            m_Account.Wait();
            Task<Account> AccountInfo = m_Account.Result.Resource();
            AccountInfo.Wait();
            Task<IOrderContext> Order = Acme.NewOrder(new[] { "*.domain.com" });
            Order.Wait();
            Uri Location = Order.Result.Location;
            IOrderContext m_IOrderContext = Acme.Order(Location);
            IAuthorizationContext Authz = Acme.Authorization(Location);

            var Challenges = Authz.Challenges();
            Challenges.Wait();
            var DnsChallenge = Authz.Dns();
            DnsChallenge.Wait();
            var HttpChallenge = Authz.Http();
            HttpChallenge.Wait();
            var TlsAlpnChallenge = Authz.TlsAlpn();
            TlsAlpnChallenge.Wait();

**Comment by webprofusion-chrisc** [comment]
I think you want to get your authorizations from `order.Authorizations()`.

Your code will be much simpler if you do all this within an `async` method and `await` the results instead of using .Wait() - generally you'd only use .Wait() if you absolutely need to run within a synchronous code block.

See the examples in the Readme for general use: https://github.com/fszlin/certes

**Comment by garsia0** [comment]
same result get null from all auth
that example is outdate some function moved => https://github.com/fszlin/certes

my code is based on = > https://github.com/fszlin/certes/blob/master/docs/APIv2.md

static async Task StartAsync()
        {
            AcmeContext Acme;
            IAccountContext m_Account;
            if (File.Exists("Account.pem"))
            {
                var accountKey = KeyFactory.FromPem(File.ReadAllText("Account.pem"));
                Acme = new AcmeContext(WellKnownServers.LetsEncryptStagingV2, accountKey);
                m_Account = await Acme.Account();
            }
            else
            {
                Acme = new AcmeContext(WellKnownServers.LetsEncryptStagingV2);
                m_Account = await Acme.NewAccount("email@gmail.com", true);
                // Save the account key for later use
                string pemKey = Acme.AccountKey.ToPem();
                File.WriteAllText("Account.pem", pemKey);
            }

            Account AccountInfo = await m_Account.Resource();
            IOrderContext Order = await Acme.NewOrder(new[] { "*.domain.com" });
            Uri Location = Order.Location;
            IOrderContext m_IOrderContext = Acme.Order(Location);
            IAuthorizationContext Authz = Acme.Authorization(Location);

            var Challenges = await Authz.Challenges();
            var DnsChallenge = await Authz.Dns();
            var HttpChallenge = await Authz.Http();
            var TlsAlpnChallenge = await Authz.TlsAlpn();
        }

**Comment by wiggisser** [comment]
@garsia0 

You **can not** get the authorization from the Acme Context using the location of the **order**, like you currently do

```c#
IOrderContext Order = await Acme.NewOrder(new[] { "*.domain.com" });
Uri Location = Order.Location;  // <-- this is the location of the order, not of a authorization
IOrderContext m_IOrderContext = Acme.Order(Location);
IAuthorizationContext Authz = Acme.Authorization(Location);  // <-- you are using the wrong location here
```

You have to either get your all authorizations from the order Context
```c#
var authz = m_IOrderContext.Authorizations();

foreach (var auth in authz) {
  var dns = await auth.Dns();
  ...
}
```

Or you you can get the authorization for a specific domain from the order Context 

```c#
var auth = await m_IOrderContext.Authorization("*.domain.com");
var dns = await auth.Dns();
```

**Comment by garsia0** [comment]
thanks last question exist any way get from server if certificate still valid and expire date or need take from certificate

**Comment by webprofusion-chrisc** [comment]
No, you should definitely read that information from your certificate.
