### ISSUE TITLE
Add root certificate while generating certificate files

### ISSUE THREAD

**Issue by wiggisser** [fszlin/certes#243]
When calling `certificateChain.Cert.toPem()` or `certificateChain.Cert.toPfx()` (ie the extension methods from `CertificateChainExtensions`) an `AcmeException` with message `Can not find issuer ...` is thrown, when the trust-anchor for this certificate is not embedded in the library. It works for LE production and staging, because these root certificates are contained in the library, but fails for instance when testing against a local pebble instance.

I agree with @webprofusion-chrisc that embedding all possible root certificates into the library is not the best way to go (like mentioned [here](https://github.com/fszlin/certes/pull/233#issuecomment-726581168) ). So I think, there should be another possibility to (reasonable) easily provide the root certificate.

I'm not too familiar with the ACME RFC, but scanning through I couldn't find a specification on how to obtain the root certificate automatically 

- It is not contained in the certificate chain which is downloaded from the ACME provider. (Only the cert and intermediates are)
- The `up` link SHOULD be present when requesting a certificate in DER format, but support for the DER format itself is optional.
- It might be possible to extract it from the system's certificate store (like registry in windows, keychain in MacOS ...) but that 
    - may not be possible on all platforms, 
    - requires platform specific code and 
    - does not solve the problem, that the root certificate may not even be known to the system

As possible workaround I could provide a PR which allows to provide the root certificate to `CertificateChainExtensions.ToPfx()` and `CertificateChainExtensions.ToPem()` (similar to what's done in the Certes.CLI with the `--issuer` option already). So anyone using this library with a CA other than LetsEncrypt can at least pre-download the root certificate and include it in the workflow.

**Comment by webprofusion-chrisc** [comment]
In Certify (which uses certes) I pull the list of trusted roots from the computer store and add them to the list of possible issuers certs, this means you can build an cert chain with any known trusted root. If the root doesn't exist in the computer store then it fails.

I wonder if instead we could provide a specific API to add/append known issuers and if the cert chain fails to build we throw a specific exception to identify that as the exact cause. Other causes can include system time being incorrect (cert is in the future).

**Comment by wiggisser** [comment]
@webprofusion-chrisc I thought about the computer store too, but couldn't find an easy way to provide these certificates to certes.

**Comment by wiggisser** [comment]
@webprofusion-chrisc The real problem is not creating a pfx, as you always can add a bunch of additional certificates (from whatever source) to the PfxBuilder after it's returned from CertificateChainExtensions.ToPfx(). Just like you do in Certify. Then the PfxBuilder will search for the correct root. 

But when creating a PEM with `CertificateChainExtensions.ToPem()`, you don't have this possiblity. One can --of course -- not just add a bunch of possible root certs to the certificate chain beforehand. But you have to find the correct root certificate and append it to the chain yourself, because the certStore which is used to resolve the issuers is only created within that extension method.

I would also prefer a more general approach, but couldn't find any reasonable place where to keep track of those trusted certificates. In the end of the day, one has to make them accessible from the CertificateChain class or its extension methods, but currently that leaves only these possibilities (if keeping backwards compatibility)

1. Add them as an optional collection to the CertificateChain class itself, before calling ToPfx or ToPem
2. Pass them when calling ToPem()
3. put them in some `public static` property, which IMHO contradicts the idea of separate contexts.

and then when calling ToPem()/ToPfx() the trusted roots can be added to the newly created certificate store/PfxBuilder.

**Comment by webprofusion-chrisc** [comment]
Thanks, yes agree that instead of us scraping around for the proper root cert the ACME CA should have an endpoint that serves the public root certs for the chains they support. It looks like this may have become part of pebble but isn't part of ACME
: https://github.com/letsencrypt/pebble/issues/152

**Comment by wiggisser** [comment]
While trying to find a decent workaround, I also discovered that currenty, there is no possibility to add an additional issuer-certificate to an existing CertificateChain (like the one that is returned from `orderCtx.Download`). So it seems, there is no possibility to create certificate in PEM format for any CA other than letsencrypt but converting each of the IEncodable contained in the chain (Certificate and Issues) and also root issuer separately to PEM and then concatenating those single PEM certificates to a combined one.

**Comment by webprofusion-chrisc** [comment]
Yes, in Certify we use the final PFX to then do conversion to pem file components (if required for exports etc).
