### ISSUE TITLE
What is NuGet package v2.3.4?

### ISSUE THREAD

**Issue by ygoe** [fszlin/certes#244]
There's a NuGet package with the version 2.3.4 of this library, but its release notes or code tag cannot be found in this repository, that's still at 2.3.3 of some two years ago. Which version should I use for a new project, 2.3.3 or 2.3.4 or latest master? (Targeting .NET Core 3.1, probably soon upgrading to 5.0)

**Comment by webprofusion-chrisc** [comment]
Hi, not sure but I'd use latest master as it has recently had a number of useful features added.

2.3.4 (currently not tagged) is equivalent to the snapshot of master at 2020/03/27, https://github.com/fszlin/certes/commit/8e8bec31dbf4644a4ce0760e28c15009b827f611

**Comment by webprofusion-chrisc** [comment]
See also #240

**Comment by webprofusion-chrisc** [comment]
See also my minor fork for packaging purposes. This has newer features than the standard certes NuGet package. : https://www.nuget.org/packages/Webprofusion.Certes
