### ISSUE TITLE
Create a NuGet package on build

### ISSUE THREAD

**Issue by ygoe** [fszlin/certes#245]
I wanted to create a NuGet package from the latest master so I can actually use this library. But I failed. Here's what I did:

```
set AssemblyVersion=2.3.5
set PackageVersion=2.3.5-dev+48e3ba

dotnet restore -v q
cd src\Certes
dotnet publish -c Release --no-restore -nologo -p:AssemblyVersion=%AssemblyVersion% -p:InformationalVersion=%PackageVersion% -p:DebugSymbols=true -p:DebugType=embedded -p:EmbedAllSources=true
dotnet pack -c Release -nologo -p:PackageVersion=%PackageVersion%
```

This did build the DLL but no package. I tried to set `GeneratePackageOnBuild=true` on publish first, as that's the property I've set in my library projects, but it had no effect. Then I found the `dotnet pack` command to do it separately, but it fails and can't find the DLL in the net45 directory when it really is in the netstandard2.0 directory. Very strange.

```
C:\Program Files\dotnet\sdk\5.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.EolTargetFrameworks.targets(28,5): warning NETSDK1138: Das Zielframework "netcoreapp3.0" wird nicht mehr unterstützt und erhält in Zukunft keine Sicherheitsupdates mehr. Weitere Informationen zur Supportrichtlinie finden Sie unter "https://aka.ms/dotnet-core-support". [C:\Source\Web\certes\test\Certes.Tests.Web\Certes.Tests.Web.csproj]
  Certes -> C:\Source\Web\certes\src\Certes\bin\Release\netstandard2.0\Certes.dll
  Certes -> C:\Source\Web\certes\src\Certes\bin\Release\netstandard2.0\publish\
  Certes -> C:\Source\Web\certes\src\Certes\bin\Release\netstandard2.0\Certes.dll
C:\Program Files\dotnet\sdk\5.0.100\Sdks\NuGet.Build.Tasks.Pack\build\NuGet.Build.Tasks.Pack.targets(207,5): error NU5026: Die im Paket einzubeziehende Datei "C:\Source\Web\certes\src\Certes\bin\Release\net45\Certes.dll" wurde auf dem Datenträger nicht gefunden. [C:\Source\Web\certes\src\Certes\Certes.csproj]
```

Maybe a simple additional build script doesn't help here and I need to delete and recreate the entire project file to make it work.

How does everybody else use this library in the latest version? Copy the DLL into your project? And all of its dependencies?

Update: I tried to recreate the .csproj file but that won't build anymore. It can't find any type from mscorlib anymore. Something is seriously broken with this code that prevents it from building with the usual and simple methods. All those imports look pretty complicated. I'm using the 2.3.4 package on nuget.org now, later features are just not available.

**Comment by AMEST** [comment]
@ygoe Hi, I also needed the latest library changes for my project, which are in master, but have not yet been released in nuget. Essentially, I was able to gather basic library on the current version of the master and released as it unstable release (nightly builds). 
You can see the package assembly algorithm here https://github.com/AMEST/certes/blob/master/.github/workflows/main.yml or use the already assembled package https://www.nuget.org/packages/Nightly-Certes
I will try, whenever possible, to rebase from the main repository and release such a nightly build.

**Comment by webprofusion-chrisc** [comment]
For info I have also now published `Webprofusion.Certes` : https://www.nuget.org/packages/Webprofusion.Certes/ this version is as used by https://certifytheweb.com and is supported.

**Comment by ygoe** [comment]
Wontfix and closed? No new release in several years? Does this mean this project is now officially unmaintained? Maybe I should look for an alternative then before relying on this for too long.

**Comment by ygoe** [comment]
@webprofusion-chrisc Your fork doesn't have an issue tracker and there are inconsistencies in the tags and changelog. Also, GitHub says your fork is many commits behind this one. That doesn't look like an updated copy of this yet. Maybe I need to continue my search for a more future-proof ACME client. This Certes project here is certainly dead.

**Comment by webprofusion-chrisc** [comment]
@webprofusion-chrisc yes it's mainly for my own use, the main project here has adjusted some things to target .net 5/6 but my project still targets .net 4.6.2 - use it if you want, or fork your own.
