### ISSUE TITLE
Cancel authorisations or orders

### ISSUE THREAD

**Issue by ygoe** [fszlin/certes#246]
When I started an order and tried to complete the challenges, but in the middle of the process I realised that I cannot complete the order and challenges, what should I do? I've read in the [LetsEncrypt documentation](https://letsencrypt.org/docs/rate-limits/) that there must not exist too many pending authorisations for an account. I thought I have to cancel those (or the orders) before I can proceed with other orders. I didn't find an API for that, though. Is this implemented? Or am I getting this wrong? How long can these pending authorisations accumulate?

With a limit of 300 this may seem like a silly question, but whenever I can I like to implement things in a robust way so that I never have to worry about them again. And my program detects that case (like if the application was restarted or the user has changed their mind quickly) so I should handle it.

**Comment by webprofusion-chrisc** [comment]
You should submit your challenge responses and let them fail, they will no longer be pending. ACME doesn't have a cancel pending authorization function.
