### ISSUE TITLE
DnsChallenge.Resource() does not refetch status

### ISSUE THREAD

**Issue by UnoSD** [fszlin/certes#249]
Thank you for this library.

Unfortunately, I am struggling to get the verification working in one run; it feels like somewhere the response gets cached or I am misusing the library. I have not seen an example of v2 in the docs to follow.

given this code:

```f#
let acme = AcmeContext(WellKnownServers.LetsEncryptStagingV2)

acme.NewAccount("email@my.domain", true) |>
Async.AwaitTask |>
Async.RunSynchronously |>
ignore

let pemKey = acme.AccountKey.ToPem()

let order =
    acme.NewOrder([| "*.my.domain" |]) |>
    Async.AwaitTask |>
    Async.RunSynchronously
        
let authz =
    order.Authorizations() |>
    Async.AwaitTask |>
    Async.RunSynchronously |>
    Seq.head
    
let dnsChallenge =
    authz.Dns() |>
    Async.AwaitTask |>
    Async.RunSynchronously

let dnsTxt =
    acme.AccountKey.DnsTxt(dnsChallenge.Token)
 
printfn $"""Add txt record: {dnsTxt}
To: _acme-challenge.my.domain"""

let rec validationResult (result : Task<Challenge>) =
    result |>
    Async.AwaitTask |>
    Async.RunSynchronously |>
    (fun result -> Async.Sleep(500) |> Async.RunSynchronously
                   printfn "%A: %A: %A" result.Validated result.Status (if result.Error = null then "" else result.Error.Detail)
                   match result.Status |> Option.ofNullable with
                   | Some ChallengeStatus.Pending
                   | Some ChallengeStatus.Processing
                   | Some ChallengeStatus.Invalid    -> dnsChallenge.Resource() |> validationResult
                   | Some ChallengeStatus.Valid      -> result.Status.Value
                   | _                               -> failwith "WUT?")
                   
dnsChallenge.Validate() |>
validationResult |>
printfn "Validation: %A"
```

It seems that `dnsChallenge.Resource()` gives always the same error:

`Invalid: "Incorrect TXT record "AAAAA" found at _acme-challenge.my.domain"`

if I update the TXT record while it's running, it does not pick up the change.

If I stop and restart the application, it then shows the new value "BBBB" (although, this time it is after "CCCC").

I got it to work only by reloading the same account after stopping and starting the application.

can you please advise if this is a bug or I am misusing the library?

Btw, can Validate be run before adding the record then checking with Resource?

Thank you

**Comment by webprofusion-chrisc** [comment]
Hi, I'm not familiar with F# enough to comment on the code but what you should be trying to do (and I think you mostly are) is:
- place your certificate order with Let's Encrypt
- fetch the required challenges you want to attempt (Dns)
- complete the challenge - in this case you have to add the _acme-challenge record to your domains DNS with the required TXT value (you should set a short TTL to encourage quick replication). 

You then need to wait for all of your DNS nameservers to report this TXT value. You can check this using the linux dig command: `dig - t TXT _acme-challenge.yourdomain.com`. Let's Encrypt may use any of your nameservers so they must all be up to date. Sometime this takes a few seconds, but on some providers this can take up to an hour.

- if you then ask Let's Encrypt to Validate your challenge response, it will go ahead and check your DNS txt record, if the value isn't (yet) what it expects to see then the challenge has failed - you will be asked to create a different record next time you attempt the request.
- if the TXT record value is correct (for all the domains on your order) then you can proceed to finalising the order and downloading your certificate.

**Comment by UnoSD** [comment]
hi @webprofusion-chrisc , thank you for the response.

as I suspected, my approach of `Validate` before actually adding the record is not suitable.

I will try and add and verify that the record is in place before calling `Validate` with some DNS lookup library, hopefully that will solve it. I would like my code to be fully automated and not to require human intervention to check the DNS before sending the Validate.

Shall I verify this first before closing the issue?

**Comment by webprofusion-chrisc** [comment]
Thanks, yes you could perhaps poll in a loop until you see the TXT record - the ideal way is to use an API to update DNS (so the user doesn't have to), then wait for DNS (nameserver) propagation, then validate the challenge response.

**Comment by UnoSD** [comment]
Just for testing I put a `Console.ReadKey()` and set up the record before `Validate()` and it worked. Thank you again.
