### ISSUE TITLE
Reusing registered accounts

### ISSUE THREAD

**Issue by ericallenpaul** [fszlin/certes#25]
As I understand it, a Let's Encrypt account only needs to be registered one time.
So if I call:

`var account = await client.NewRegistraton($"mailto:{Email}");`

I need to save the account so I can re-use it on future registrations. (According to the LE documentation there is a penalty for registering a single account too many times.)
I can re-use the registered account by calling the Use method:

`client.Use(account.Key);`

What I can't figure out is how to save the key in my database so I can re-use it later.
The key is a type KeyInfo but it only contains one property "PrivateKeyInfo". I can store this byte array but I need a way to turn it back into a key. Do you have any examples of how to do that?

**Comment by fszlin** [comment]
Hi @ericallenpaul, the `PrivateKeyInfo` is essentially the key in DER format.
Are you looking to store in a different format?

**Comment by ericallenpaul** [comment]
First, thanks for such a quick reply.

I have a class `LeAccount` it has a property `public virtual byte[] LeKey { get; set; }`. After I register the account I save it in my DB. I have a method: 

```
private async Task<LeAccount> GetOrCreateLeAccount(string Email)
{
            //check the database to see if there is an existing account with that email address
            LeAccount returnValue = _Context.LeAccounts.First(x => x.Email == Email); 
            
            //if there is an existing account then return it
            if (returnValue != null)
            {
                return returnValue;
            }

            //if no account exists for this email address
            //create a new let's encrypt account
            using (var client = new AcmeClient(GetLeServers()))
            {
                //send the account request to Let's encrypt
                var account = await client.NewRegistraton($"mailto:{Email}");

                if (account != null)
                {
                    // Accept terms of services
                    account.Data.Agreement = account.GetTermsOfServiceUri();
                    account = await client.UpdateRegistration(account);

                    //store the account in the database
                    returnValue = new LeAccount
                    {
                        Email = Email,
                        AgreementUri = account.Data.Agreement.ToString(),
                        CreatedDate = DateTime.Today,
                        LastModifiedDate = DateTime.Today,
                        LeKey = account.Key.PrivateKeyInfo,
                        LeAccountId = account.Location.AbsoluteUri
                    };

                    _Context.LeAccounts.Add(returnValue);
                    _Context.SaveChanges();
                }
                else
                {
                    throw new Exception("Error: Unable to register account.");
                }
            }

            //return the account
            return returnValue;
 }
```

Then in my `GetCertificate()` I have:

```
var account = await GetOrCreateLeAccount(_SslSettings.LeRegistrationEmail);
client.Use(DONT_KNOW_WHAT_TO_PUT_HERE);
```
Since I'm only saving the byte array in the database and `byte[]` is not `KeyInfo` I think I need some way to turn the byte array back into `KeyInfo`. Something like:

```
var account = await GetOrCreateLeAccount(_SslSettings.LeRegistrationEmail);
KeyAlgorithmProvider keyAlgorithmProvider = new KeyAlgorithmProvider();
var keyInfo = keyAlgorithmProvider.GetKeyPair(account .PrivateKeyInfo);
client.Use(keyInfo);
```

I hope this explains what I'm trying to do.

**Comment by fszlin** [comment]
I think all you need for restoring the key is `new KeyInfo { PrivateKeyInfo = account.LeKey; }`

It looks like you are using v2.0 beta, if you are looking to build around ACME v2, check the [API here](https://github.com/fszlin/certes/blob/master/docs/APIv2.md).
`AcmeClient` only works for ACME v1.

**Comment by ericallenpaul** [comment]
Perfect! That is exactly what I needed.

Thanks also for all of your hard work creating this library. It's made my job a lot easier.

**Comment by fszlin** [comment]
☺️   closing the issue.
