### ISSUE TITLE
Not possible to build solution locally

### ISSUE THREAD

**Issue by peterM** [fszlin/certes#251]
When i downloaded code and try to build i am getting error. My VS is not able to resolve reference for type `ArgumentCommand<>` and `ArgumentSyntax`
Thanks.

**Comment by webprofusion-chrisc** [comment]
From memory to build the whole solution you need to reference myget (which is no longer available) as it was using an experimental version of the CLI argument library. Just remove the cli project and built without it.

**Comment by peterM** [comment]
Yes I did it this way. :) Thanks
