### ISSUE TITLE
Why Order's status ("invalid") for wildcard certificates?

### ISSUE THREAD

**Issue by kyuranger** [fszlin/certes#252]
I am about to create wildcard certificates.

Here is my code:
`              var context = await Login();
                var order = await context.NewOrder(new[] { "*.abc.com" });
                var certKey = KeyFactory.NewKey(KeyAlgorithm.RS256);                
                var authz = (await order.Authorizations()).First();
                var dnsChallenge = await authz.Dns();                
                var httpChallenge = await authz.Http();
                var tlsAlpnChallenge = await authz.TlsAlpn();
                var dnsTxt = context.AccountKey.DnsTxt(dnsChallenge.Token);
                var DNSFile = @"C:\ACMEProject\1234";
                if (File.Exists(DNSFile))
                {
                    File.Delete(DNSFile);
                }
                File.WriteAllText(DNSFile, dnsTxt);
                var challenges = await authz.Challenges();
                var alpnCertKey = KeyFactory.NewKey(KeyAlgorithm.ES256);
                var alpnCert = context.AccountKey.TlsAlpnCertificate(challenges.First().Token, "*.abc.com", alpnCertKey);
                var challenge=await challenges.First().Validate();
                int tryCount = 1;
                while (challenge.Status == ChallengeStatus.Pending && tryCount <= 10) {
                    tryCount++;
                    await Task.Delay(1000);
                }
                if (challenge.Status != ChallengeStatus.Valid)
                {
                    await order.Finalize(
                    new CsrInfo
                    {
                        CountryName = "CountryName",
                        State = "State",
                        Locality = "Locality",
                        Organization = "Organization",
                    }, certKey);
                    var certChain = await order.Download();
                    File.WriteAllText("Generated.pem", certChain.ToPem());
                }`

The web server I am using is IIS.

What I wrote a file to C:\ACMEProject\1234 is for adding dnsTxt value to _acme-challenge.abc.com according to the tutorial.

And also, here is the code in ACMEProject. It is only for DNS validation:
`public class AcmeController : ControllerBase
    {
        [Route("/")]
        public IActionResult DNSCertification()
        {            
            if (System.IO.File.Exists("1234"))
            {
                return Ok(System.IO.File.ReadAllText("1234"));
            }
            else
            {
                Response.StatusCode = 404;
                return NotFound();
            }
        }
}`

After all the codes ran, it reports the error below:
Certes.AcmeRequestException: Fail to load resource from 'https://acme-staging-v02.api.letsencrypt.org/acme/finalize/18424772/3723369'.
urn:ietf:params:acme:error:orderNotReady: Order's status ("invalid") is not acceptable for finalization
   at Certes.Acme.IAcmeHttpClientExtensions.Post[T](IAcmeHttpClient client, Uri uri, Object payload, Boolean ensureSuccessStatusCode)
   at Certes.Acme.OrderContext.Finalize(Byte[] csr)
   at Certes.IOrderContextExtensions.Finalize(IOrderContext context, CsrInfo csr, IKey key)

What's wrong with my code? Thank you.

**Comment by webprofusion-chrisc** [comment]
Hi the issue is that your DNS validation challenge has failed, this is usually because when you asked Let's Encrypt to validate that you ad completed the challenge your DNS settings had not fully propagated to all your nameservers, or your update to the DNS TXT record was incorrect.

With IIS, I'd recommend you consider if you can use https://certifytheweb.com to manage your certificates, this is the software I develop and it's easier than developing and supporting your own ACME client code.

**Comment by kyuranger** [comment]
> Hi the issue is that your DNS validation challenge has failed, this is usually because when you asked Let's Encrypt to validate that you ad completed the challenge your DNS settings had not fully propagated to all your nameservers, or your update to the DNS TXT record was incorrect.
> 
> With IIS, I'd recommend you consider if you can use https://certifytheweb.com to manage your certificates, this is the software I develop and it's easier than developing and supporting your own ACME client code.

Thank you very much!
