### ISSUE TITLE
Can not find issuer 'C=US,O=(STAGING) Internet Security Research Group,CN=(STAGING) Doctored Durian Root CA X3' for certificate 'C=US,O=(STAGING) Internet Security Research Group,CN=(STAGING) Pretend Pear X1'.

### ISSUE THREAD

**Issue by 102425074** [fszlin/certes#253]
Here is my code:

var context = await Login();
                var order = await context.NewOrder(new[] { "*.sample.com" });
                var certKey = KeyFactory.NewKey(KeyAlgorithm.RS256);                
                var authz = (await order.Authorizations()).First();
                var dnsChallenge = await authz.Dns();                
                var httpChallenge = await authz.Http();
                var tlsAlpnChallenge = await authz.TlsAlpn();
                var dnsTxt = context.AccountKey.DnsTxt(dnsChallenge.Token);
                await AddDomainRecord(dnsTxt);
                var challenges = await authz.Challenges();
                var alpnCertKey = KeyFactory.NewKey(KeyAlgorithm.ES256);
                var alpnCert = context.AccountKey.TlsAlpnCertificate(challenges.First().Token, "*.sample.com", alpnCertKey);
                var challenge=await challenges.First().Validate();
                int tryCount = 1;
                while (challenge.Status == ChallengeStatus.Pending && tryCount <= 10) {
                    tryCount++;
                    await Task.Delay(1000);
                }
                if (challenge.Status == ChallengeStatus.Valid)
                {                  
                    await order.Finalize(
                    new CsrInfo
                    {
                        CountryName = "CountryName ",
                        State = "State ",
                        Locality = "Locality ",
                        Organization = "Organization ",
                    }, certKey);
                    var certChain = await order.Download();
                    var privateKey = KeyFactory.NewKey(KeyAlgorithm.ES256);
                    var pfxBuilder = certChain?.ToPfx(privateKey);
                    var PemContent = await ReadCAPEM();
                    PemContent = PemContent.Replace("-----BEGIN CERTIFICATE-----", "");
                    PemContent = PemContent.Replace("-----END CERTIFICATE-----", "");
                    PemContent = PemContent.Replace("\r\n", "");
                    PemContent = PemContent.Replace(" ", "");
                    Logger.LogInformation("PemContent:" + PemContent);
                    pfxBuilder.AddIssuer(Convert.FromBase64String(PemContent));
                    byte[] B = pfxBuilder.Build("*.sample.com", "123456");
                    File.WriteAllText("Generated.pfx", System.Text.Encoding.UTF8.GetString(B));
                }

After the code ran, it reports this error:
Can not find issuer 'C=US,O=(STAGING) Internet Security Research Group,CN=(STAGING) Doctored Durian Root CA X3' for certificate 'C=US,O=(STAGING) Internet Security Research Group,CN=(STAGING) Pretend Pear X1'.
   at Certes.Pkcs.CertificateStore.GetIssuers(Byte[] der)
   at Certes.Pkcs.PfxBuilder.FindIssuers()
   at Certes.Pkcs.PfxBuilder.Build(String friendlyName, String password)

It seems the problem similar to https://github.com/fszlin/certes/issues/248.

However, it solved by grabbing a new certificate binary while I can not find any about this.

I am not sure but it seems I need to find an SSL certificate issuer for it, right?

How can I solve this? Thank you.

**Comment by webprofusion-chrisc** [comment]
As mentioned here: https://community.letsencrypt.org/t/can-not-find-issuer-c-us-o-staging-internet-security-research-group-cn-staging-doctored-durian-root-ca-x3-for-certificate-c-us-o-staging-internet-security-research-group-cn-staging-pretend-pear-x1/147613

You should use pfxBuilder.AddIssuers to add the unknown issuer certs to be used by the pfx builder.

**Comment by qideqian** [comment]
依旧还是这个错误，是否因为DST ROOT CA X3根证书已经过期的原因？ @webprofusion-chrisc

**Comment by qideqian** [comment]
证书已于2021.9.30过期
