### ISSUE TITLE
Why I can't convert to a PEM file?

### ISSUE THREAD

**Issue by kyuranger** [fszlin/certes#254]
Here is my code:
await order.Finalize(
                    new CsrInfo
                    {
                        CommonName= "*.sample.com",
                        CountryName = "CountryName ",
                        State = "State ",
                        Locality = "Locality ",
                        Organization = "Digital Signature Trust Co.",
                    }, certKey);
                    var certChain = await order.Download();
                    var a=certChain?.ToPem();
                    File.WriteAllText("Generated.pem", a);

After the program ran, it reports this error:
 Can not find issuer 'C=US,O=(STAGING) Internet Security Research Group,CN=(STAGING) Doctored Durian Root CA X3' for certificate 'C=US,O=(STAGING) Internet Security Research Group,CN=(STAGING) Pretend Pear X1'.

It is similar as https://github.com/fszlin/certes/issues/253

I solve it by add an issuer and convert it to pfx:
await order.Finalize(
                    new CsrInfo
                    {
                        CommonName= "*.sample.com",
                        CountryName = "CountryName ",
                        State = "State ",
                        Locality = "Locality ",
                        Organization = "Digital Signature Trust Co.",
                    }, certKey);
                    var certChain = await order.Download();
var privateKey = KeyFactory.NewKey(KeyAlgorithm.ES256);
                    var pfxBuilder = certChain?.ToPfx(privateKey);
                    pfxBuilder.AddIssuer(System.IO.File.ReadAllBytes("3958242236.crt"));
                    byte[] B = pfxBuilder.Build("*.sample.com", "123456");
                    File.WriteAllText("Generated.pfx", System.Text.Encoding.ASCII.GetString(B));

However, even it built the pfx successfully but after I convert it to pem by this tool:https://www.sslshopper.com/ssl-converter.html

It always reports the password(123456) is incorrect.

What's the matter with this? I have converted any other pfx to pem by this website many times before. It should work.

**Comment by Lakerfield** [comment]
See https://github.com/webprofusion/certes/pull/2 The new letsencrypt staging root is not in the certificatestore of the library
