### ISSUE TITLE
Multi domains in a DnsOrder allowed?

### ISSUE THREAD

**Issue by ruicaramalho** [fszlin/certes#255]
Hi

can I make a order like the example bellow:

~~~~csharp
IOrderContext order = await acme.NewOrder(new[] { "*.domain1.com","domain1.com","*.domain2.com","domain2.com" });
~~~~
If yes:
 - How many Authorizations wil this produce, just one? or one for each element on the array?
 - If more than one, how do I know in `IEnumerable<IAuthorizationContext>` what is the domain to place the `TXT` record?

~~~~csharp
IEnumerable<IAuthorizationContext> authzs = await order.Authorizations();
~~~~

Thanks

**Comment by Lakerfield** [comment]
For every element in the array there is a separate authorization.
Your example should return 4 times a IAuthorizationContext in the order of the hostnames in the order array.

While validating there should be 2 _acme-challenge.domain1.com records and 2 _acme-challenge.domain2.com records in the dns.

**Comment by ruicaramalho** [comment]
Thanks
