### ISSUE TITLE
Renew Certificate without updating dnsTXT record 

### ISSUE THREAD

**Issue by getsolomon** [fszlin/certes#257]
Hi fszlin/Certes Team,

I am using Certes client for generating Let's encrypt certificate.

I have generated a certificate using a dns validation and dnsTXT record is placed in customer's domain. Can I get renewal certificate using the same dnsTXT which is in customer domain? 
Because it is difficult to ask customer to replace their TXT records every 90 days .

**Comment by webprofusion-chrisc** [comment]
Hi, no Let's Encrypt will change the required TXT record value for every new certificate order. You could either:
- ask your customer to create a CNAME (instead of the TXT record) with the same `_acme-challenge.<customerdomain.com>` name pointed to a domain you control, then you can update that automatically as required
- or check out acme-dns, which is the same idea but you update the acme-dns service instead of changing DNS every time.

**Comment by getsolomon** [comment]
Thanks Chris. The second option you mentioned will work only if self-hosted server is set up. 

But I am using Certes client for downloading Certificate. Is there a way to automate renewals using Certes or something without client installations? 

Thanks

**Comment by webprofusion-chrisc** [comment]
The Certes library itself doesn't offer automated renewals but the old command line stuff might. I personally develop https://certifytheweb.com which is a GUI for managing certificates - it uses Certes and also has automatic renewals ( it runs as a background service). We have also developed a managed (cloud hosted) version of acme-dns which may soon become a service offered to Certify users, so they don't have to run their own acme-dns server.

**Comment by getsolomon** [comment]
certifytheweb look like a fantastic tool. But I cannot install it on my AWS hosted servers. 

So, I am checking to see if I can do the automation programmatically. Can you suggest any other (library) options to do renewals programmatically without installations?

Thanks

**Comment by webprofusion-chrisc** [comment]
Hi, No problem, I'm assuming you're on Windows? 

For other command line based automations you can check out certbot (https://certbot.eff.org/) which uses a scheduled task for renewals (windows or linux), Again, assuming you're on windows there is also win-acme, Posh-ACME and a few other tools: https://letsencrypt.org/docs/client-options/

**Comment by getsolomon** [comment]
Hi Chris,

If using HTTP-01 challenge, don't we need to replace the file in "<domain.com>/.well-known/acme-challenge/<Token> " every time the certificate is renewed?

Schoen suggests somewhere in his replies -

https://community.letsencrypt.org/t/do-i-have-to-change-my-txt-recordds-every-30-days/58546/5

**"With HTTP-01, a CNAME to an A record for an IP address is already enough control to obtain a certificate, without having to post any DNS records—you just have to be able to serve a specified file over HTTP on port 80 of the IP address."**

Thanks,

**Comment by webprofusion-chrisc** [comment]
Yes, every certificate order will result in new domain validation, so the "challenge" changes each time and you have to present a new file with new challenge response content. You can optionally redirect these /. well-known/acme-challenge requests all to another server if you want to but it must know the challenge answer to serve.

You didn't confirm if you're using Windows and IIS or not, but if you are there are other techniques such as a custom http listener you can use.

Can do describe more about why you are trying to use a custom acme solution instead of using an existing tool? Are you hosting your domains on Windows or Linux?

**Comment by getsolomon** [comment]
Sorry Chris. I am using Windows and has IIS. My application runs on AWS hosted servers. 

We are trying to give the customers the option of securing their sites providing the TXT record to place in their domain at their convenience.

**Comment by getsolomon** [comment]
Hi Chris,

We are planning to use the CertifyWeb GUI client. My domain _acme-challenge.sampledomain.com has TXT record 'asdfasdfasdf'. 

Now in CertifyWeb, I am using API provider 'acme-dns DNS API'. The test is successful. But certificate is not generated and throws an error something like this - 

Validation of the required challenges did not complete successfully. Incorrect TXT record "JuXVCgRueO_mXIVfNN_qpIX0BQpLbhDoDu2ywKTAHCU" found at '_acme-challenge.sampledomain.com'

What should my TXT record should contain in customer domain?? Should it be acme-dns api value like 
ae8e8c02-8224-44af-a311-988bd17a19e9.auth.acme-dns.io??

**Comment by webprofusion-chrisc** [comment]
So when you first use Certify with the acme-dns provider set and click either **Test** or **Request Certificate** it will show a message telling you to create a **CNAME** dns record, in this case it wants you to create a CNAME (not a TXT record) called `_acme-challenge` in the domain DNS and point it to  `ae8e8c02-8224-44af-a311-988bd17a19e9.auth.acme-dns.io`

A CNAME record in DNS is basically a redirection from the record in your DNS to a record elsewhere, in this case it points to the acme-dns service. When you then setup that CNAME, wait 60 seconds or so for DNS servers to update then click 'Request Certificate', this will then set the TXT record on the acme-dns server to the value required.

If you need further help debugging this scenario you can email support {at} certifytheweb.com and we can discuss it there, this github issue is not related to Certify so it's not really the right place to discuss Certify related support topics.
