### ISSUE TITLE
Get the certificate information after registration

### ISSUE THREAD

**Issue by ericallenpaul** [fszlin/certes#26]
How would I go about getting the certificate information after it's registered?

```
var cert = await client.NewCertificate(csr);
```
Given the code above, would I use `cert.Json` and just parse the results or is there an easier way?

**Comment by fszlin** [comment]
You may use [X509Certificate2](https://msdn.microsoft.com/en-us/library/system.security.cryptography.x509certificates.x509certificate2) or any library that understand X509 certificate.

```C#
var x509Cert = new X509Certificate2(cert.Raw);
```

**Comment by ericallenpaul** [comment]
If I'm ever in Toronto I owe you a beer--or maybe a case of beer 👍
