### ISSUE TITLE
DNS Challenge results in one of two errors

### ISSUE THREAD

**Issue by rsioo** [fszlin/certes#261]
Hello,

I have a problem regarding the DNS Challenge. For some domains it works just fine, for others I can only generate a wildcard certificate but not a certificate for just `example.com`. I can't disclose the domains here but what I can say is that we use `euroDNS` as a DNS provider. They have an API but I believe that there is a already an issue: When adding a new record to the zone, the minimum TTL that I can provide is 600 seconds. Is that too long of a TTL for the acme protocol to work correctly?

The errors that I get are one of the 2:

1. Either I get the error `DNS problem: NXDOMAIN looking up TXT for _acme-challenge.example.com - check that a DNS record exists for this domain`. I know that the record has been added successfully since I can see it in the web interface of the DNS Zone. And i can see the records when using any of the DNS lookup tools (dig, mxtoolbox, nslookup, [server-daten](https://check-your-website.server-daten.de), etc.)

The code that I use to do the dnsValidation is the following (just in case it could be usefull):
```c#
var result = await dnsChallenge.Validate();

    var attempts = 0;
    var maxAttempts = 10;

    while (attempts < maxAttempts && (result.Status == ChallengeStatus.Pending || result.Status == ChallengeStatus.Processing))
    {
        Logger.WriteLine(Logger.Level.Low, $"Attempt {attempts + 1} for DNS Validation. Current status: {result.Status}");
        result = await dnsChallenge.Resource();
        System.Threading.Thread.Sleep(2000);
        attempts++;
    }
```
The thing is that the code never goes further than Attempt number 3. Either it succeeds or it will result in an invalid check.

2. The other error that I get is: `Incorrect TXT record "lrFZIdrwN6-YG3ey65eyQ1Y-uQC-_G9s6ry_AOpGDRQ" (and 2 more) found at _acme-challenge.example.com`. This happens after a while of not deleting records that are there from older challenges. But if I delete the records after doing the check, I go back to error number 1. Is this due to the TTL of 600 seconds mentioned in the first paragraph?

What are some things in general that I need to do in order for it to potentially solve the issue?

Cheers everyone

**Comment by webprofusion-chrisc** [comment]
When you generate a certificate that includes both `*.domain.com` and `domain.com` you get two authorizations (one for each identifier). In the case of wildcards that actually updates the same `_acme-challenge.domain.com` but with a different value. That's just a quirk of ACME and it's not very intuitive. With most DNS providers you can specify multiple TXT record values to accommodate this. 

You then submit each distinct challenge for validation (one for each identifier on the cert), then poll the order (or challenge) to see if the auth has validated or not. Once all are validated you can proceed to finalise the order and download your certificate.
