### ISSUE TITLE
urgent issue certificate wrong root

### ISSUE THREAD

**Issue by koobooteam** [fszlin/certes#275]
We use your library to generate SSL certificates for our clients, working very fine before. 

Recently our website failed with SSL, we have reached out to Lets encrypt for help. They point out that we are using some old root certificate which are hard coded in the system. 

Can someone help this urgently, because a lot of our sites are down!

**Comment by esw0000000** [comment]
Please see issue #248 for an explanation of the issue and fix.

**Comment by webprofusion-chrisc** [comment]
You need the ISRG Root X1 (self signed) added as an issuer.
