### ISSUE TITLE
Should remove Expired "DST Root CA X3" Root Certificate from the Embedded Certificates?

### ISSUE THREAD

**Issue by jadiagaurang** [fszlin/certes#276]
Let's Encrypt has expired **DST Root CA X3** root certificate on September 30, 2021. The repo has the same certificate in the Embedded Certificates directory which is expired as well.

The expired certificate is still getting added to the certificate chain from the [GetIssuers](https://github.com/fszlin/certes/blob/417513fad6ddb3913a5a4e8f997a45a88c0c0afc/src/Certes/Pkcs/CertificationStore.cs#L65) method from the [CertificationStore.cs](https://github.com/fszlin/certes/blob/417513fad6ddb3913a5a4e8f997a45a88c0c0afc/src/Certes/Pkcs/CertificationStore.cs#L65)!

I was thinking to add condition in the [ToPem](https://github.com/fszlin/certes/blob/417513fad6ddb3913a5a4e8f997a45a88c0c0afc/src/Certes/Extensions/CertificateChainExtensions.cs#L63) method in the [CertificateChainExtensions.cs](https://github.com/fszlin/certes/blob/417513fad6ddb3913a5a4e8f997a45a88c0c0afc/src/Certes/Extensions/CertificateChainExtensions.cs#L63) file to skip expired certificate!

Is that the best way to remove the Expired Certificate from the Certificate Chain?

**Comment by copythattome** [comment]
Hi @jadiagaurang ,
I am also facing the same issue.

I saw your  [SSL Shopper](https://www.sslshopper.com/ssl-checker.html#hostname=www.cml01.net). Looks ike you have resolved the issue.

can you tell us how you solved with Certes ACME agent API services!

**Comment by jadiagaurang** [comment]
Hi @copythattome,

I have updated Extension File called [CertificateChainExtensions.cs](https://github.com/fszlin/certes/blob/main/src/Certes/Extensions/CertificateChainExtensions.cs)

I have updated two methods to filter out expired certificate during building certificate chain!

1. [ToPfx()](https://github.com/fszlin/certes/blob/417513fad6ddb3913a5a4e8f997a45a88c0c0afc/src/Certes/Extensions/CertificateChainExtensions.cs#L20)

```
/// <summary>
/// Converts the certificate to PFX with the key.
/// </summary>
/// <param name="certificateChain">The certificate chain.</param>
/// <param name="certKey">The certificate private key.</param>
/// <returns>The PFX.</returns>
public static PfxBuilder ToPfx(this CertificateChain certificateChain, IKey certKey) {
	var pfx = new PfxBuilder(certificateChain.Certificate.ToDer(), certKey);
	if (certificateChain.Issuers != null) {
		foreach (var issuer in certificateChain.Issuers) {
			var certParser = new X509CertificateParser();
			var cert = certParser.ReadCertificate(issuer.ToDer());

			if (DateTime.Compare(cert.NotAfter, DateTime.Now) > 0) {
				pfx.AddIssuer(issuer.ToDer());
			}
			else {
				// Issuer's Certificate is Expired!
			}
		}
	}

	return pfx;
}
```

2. [ToPem()](https://github.com/fszlin/certes/blob/417513fad6ddb3913a5a4e8f997a45a88c0c0afc/src/Certes/Extensions/CertificateChainExtensions.cs#L40)

```
/// <summary>
/// Encodes the full certificate chain in PEM.
/// </summary>
/// <param name="certificateChain">The certificate chain.</param>
/// <param name="certKey">The certificate key.</param>
/// <returns>The encoded certificate chain.</returns>
public static string ToPem(this CertificateChain certificateChain, IKey certKey = null) {
	var certStore = new CertificateStore();
	foreach (var issuer in certificateChain.Issuers) {
		certStore.Add(issuer.ToDer());
	}

	var issuers = certStore.GetIssuers(certificateChain.Certificate.ToDer());

	using (var writer = new StringWriter()) {
		if (certKey != null) {
			writer.WriteLine(certKey.ToPem().TrimEnd());
		}

		writer.WriteLine(certificateChain.Certificate.ToPem().TrimEnd());

		var certParser = new X509CertificateParser();
		var pemWriter = new PemWriter(writer);
		foreach (var issuer in issuers) {
			var cert = certParser.ReadCertificate(issuer);
			if (DateTime.Compare(cert.NotAfter, DateTime.Now) > 0) {
				pemWriter.WriteObject(cert);
			}
			else {
				// Issuer's Certificate is Expired!
			}
		}

		return writer.ToString();
	}
}
```
