### ISSUE TITLE
Latest regexes produce errors

### ISSUE THREAD

**Issue by echodreamz** [fszlin/certes#279]
The latest yml files from the PHP project now include a `versions` property in the oss.yml file.

`
#webOS
- regex: '(?:Web0S; .*WEBOS|webOS|web0S|Palm webOS|hpwOS)(?:[/]?(\d+[\.\d]+))?'
  name: 'webOS'
  version: '$1'
  versions:
- regex: 'WEBOS(\d+[\.\d]+)'
   version: '$1'
- regex: 'Web0S; Linux/SmartTV.+Chrome/68'
   version: '5'
- regex: 'Web0S; Linux/SmartTV.+Chrome/53'
`

This causes runtime errors stating that Class.Os does not contain a "versions" property. To get around this, I simply added...

`        [YamlMember(Alias = "versions")]
        public Os[] Versions { get; set; }`

And the runtime error goes away, though, this is definitely not the correct fix.

**Comment by webprofusion-chrisc** [comment]
Hi, pretty sure you've got the wrong project. This is an ACME client for .net

**Comment by echodreamz** [comment]
Yup, too many windows open lol.
