### ISSUE TITLE
Add my custom generated CSR without a private key

### ISSUE THREAD

**Issue by engahmedtaha** [fszlin/certes#287]
How to add my custom iis CSR without adding private ket to Certes.IOrderContextExtensions.Generate()

**Comment by webprofusion-chrisc** [comment]
To use a custom CSR (for example in PEM format), convert it to bytes and call Finalize with the csr bytes:
```
  var csrBytes = Convert.FromBase64String(pemString);

  order = await orderContext.Finalize(csrBytes);

```
