### ISSUE TITLE
How may we renew or force renew existing certificate.

### ISSUE THREAD

**Issue by AshfaqAliZardariOfficial** [fszlin/certes#290]
I have implemented the Certes client on my c# console app, and one more thing is there any snippet to renew or force renew an existing generated domain certificate after it passed 30 days or 88 days from DateTime when the certificate was created. 

Thank You! @fszlin and the Certes team for great work!

**Comment by webprofusion-chrisc** [comment]
A renewal is just a new certificate order (it's mostly unrelated to the certificate you already have). To perform a renewal, run you certificate order again - you can do this as often as you require subject to Certificate Authority rate limits (such as duplicate certificates per week).

**Comment by AshfaqAliZardariOfficial** [comment]
Thank you again, @webprofusion-chrisc! I understand the flow to renew the certificate. 
Now, I'm closing this issue because it's resolved success. Have a good day!
