### ISSUE TITLE
Orders method not working

### ISSUE THREAD

**Issue by bugproof** [fszlin/certes#293]
Hi,

I'm trying to get list of orders using ZeroSSL's ACME v2 server.

![image](https://user-images.githubusercontent.com/3116731/170273273-3d6cfd6c-d36e-498c-9a17-1f0c12790ce2.png)

POST gives a different result saying that Content-Type and other stuff must be provided like in case of other paths. So maybe it needs to be POST and not GET? Does it work with Lets Encrypt and other CA?

**Comment by webprofusion-chrisc** [comment]
As far as I'm aware none of the popular CAs implement this feature.

**Comment by bugproof** [comment]
I see. I guess it's on their side then. Thank you for your response Christopher. I'm gonna close this one.
