### ISSUE TITLE
Error Fail to load resource from 'https://acme-v02.api.letsencrypt.org/acme/new-acct'. urn:ietf:params:acme:error:serverInternal: failed check for existing account - at Certes.Acme.IAcmeHttpClientExtensions

### ISSUE THREAD

**Issue by mmsw-git** [fszlin/certes#295]
Hello,
I use .NET based program to renew our certificates (IIS on Windows Server 2019, Certes 3.0.3). It worked well for many months. Last 2 months running from scheduler falls into error:
**Exception line:** myAccount = Await myAcme.NewAccount(My.Settings.acmeEmail, True)
**Error:** Fail to load resource from 'https://acme-v02.api.letsencrypt.org/acme/new-acct'.
urn:ietf:params:acme:error:serverInternal: failed check for existing account - at Certes.Acme.IAcmeHttpClientExtensions.

If it is run by Task Sheduler timer, it returns error.
If I run it manualy by Run button in Task Scheduler, it works well.
I cannot find any difference. Same user, same rights (highest privilege).

Thank you for your help
Miroslav

**Comment by itniels** [comment]
I am seeing this as well running create account from a linqopad script using latest `Certes (3.0.3)`
it returns a key, but when I later use the key, I get the same error message.

**Comment by cmbellman** [comment]
I think I have a similar issue, on either NewAccount or after using a acmeAccountKey on this line
`var account = await acme.Account();`

I get this stacktrace:
```
Object reference not set to an instance of an object.
   at Certes.Acme.AccountContext.<>c.<NewAccount>b__4_0(Directory d)
   at Certes.IAcmeContextExtensions.<GetResourceUri>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Certes.Acme.AccountContext.<NewAccount>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Certes.AcmeContext.<Account>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
```

@mmsw-git Did you find a solution for this? My solution also worked fine for several years, but soon my SSL certs will expire... :/

**Comment by webprofusion-chrisc** [comment]
Check that your machine is able to use TLS 1.2 when making https requests as Let's Encrypt recently retired support for previous TLS versions. Some old versions of windows (server 2012 for example) don't enable this by default, you can us IIS Crypto in Best Practices mode to auto configure windows. https://www.nartac.com/Products/IISCrypto/

**Comment by mmsw-git** [comment]
My problem was related to wrong login in Windows Service.
Miroslav

**Comment by cmbellman** [comment]
@webprofusion-chrisc Thank you, that was it! Enabled TLS 1.2 on the machine running my software and then it started to work again! It's an old win7 installation.
