### ISSUE TITLE
NewAccount

### ISSUE THREAD

**Issue by liu8857** [fszlin/certes#310]
:beer: Feel **free** to discuss anything :beer:
Executing the NewAccount method did not respond and did not report an error

**Comment by liu8857** [comment]
async await

**Comment by webprofusion-chrisc** [comment]
As you'll see from the first example on the README of this project yes the API is async and you need to await anything that makes a call to the ACME api.

```csharp
var acme = new AcmeContext(WellKnownServers.LetsEncryptStagingV2);
var account = await acme.NewAccount("admin@example.com", true);

// Save the account key for later use
var pemKey = acme.AccountKey.ToPem();
```

**Comment by liu8857** [comment]
I use webroot appaly certificate;The code is as follows
var authz = (await order.Authorizations()).First(); 
var httpChallenge = await authz.Http();
var validationFilePath = Path.Combine("/usr/share/nginx/html", httpChallenge.Token);
File.WriteAllText(validationFilePath, httpChallenge.KeyAuthz);

nginx.config
location ^~ /.well-known/acme-challenge/ {
	    allow all;
            root /usr/share/nginx/html;
        }
but nginx.error log 404?
23.178.112.106 - - [02/Aug/2023:10:42:22 +0800] "GET /.well-known/acme-challenge/uOhLxErbKqvo6JKve7tzH5huH2fXHweRCTE5EabFLgA HTTP/1.1" 404 0 "-" "Mozilla/5.0 (compatible; Let's Encrypt validation server; +https://www.letsencrypt.org)" "-"

**Comment by liu8857** [comment]
> As you'll see from the first example on the README of this project yes the API is async and you need to await anything that makes a call to the ACME api.
> 
> ```cs
> var acme = new AcmeContext(WellKnownServers.LetsEncryptStagingV2);
> var account = await acme.NewAccount("admin@example.com", true);
> 
> // Save the account key for later use
> var pemKey = acme.AccountKey.ToPem();
> ```
