### ISSUE TITLE
How to validate from ordered and authorized

### ISSUE THREAD

**Issue by BI7PRK** [fszlin/certes#77]
![default](https://user-images.githubusercontent.com/24989210/37509456-5daa6a0c-2932-11e8-927b-8a81e79e4dc6.png)

Challenges object saved to database. then i wnat to validate from Challenges object.

**Comment by fszlin** [comment]
Would this work for you?
```C#
var authz = ctx.Authorization(Challenges.AuthzUri);
var httpChallengeInfo = await authz.Http();
await httpChallengeInfo.Validate();
```

**Comment by BI7PRK** [comment]
Yes, but it throw error is:

> Unable to update challenge :: The challenge is not pending.

![default](https://user-images.githubusercontent.com/24989210/37551528-4f7a3e9e-29dc-11e8-9838-05fae5e67051.png)

**Comment by BI7PRK** [comment]
## I want to implement this process on my server: ##
###
> step 1, get Token and KeyAuthz.
> step 2. Users deploy authentication information.  (.well-know/acme-challenge/)
> step 3. validate and get a certificate.
###
e.g.  sslforfree.com, 

Can  be provide some suggestions? thanks. ^_^

**Comment by fszlin** [comment]
Sounds good, just watch for the rate limit if you are sending requests from server.

**Comment by BI7PRK** [comment]
If I understand nothing wrong, the rete limit is based on the domain name (account). It is not a server IP.

**Comment by fszlin** [comment]
Yes, you are right. I am hitting the account limit when I run tests.

**Comment by BI7PRK** [comment]
In the development, use staging environment.
https://letsencrypt.org/docs/staging-environment/
