### ISSUE TITLE
Wildcard CSR SAN names

### ISSUE THREAD

**Issue by batooo** [fszlin/certes#81]
I can create a wildcard certificate but the certificate has this data:

```
Common name: *.example.com
SANs: *.example.com
```
This means I cannot use the certificate for the raw domain (example.com).
Is this how LetsEncrypt works you are missing something in your CsrInfo?

Or maybe I need to make an order for both, *.example.com and example.com?

**Comment by fszlin** [comment]
When using CsrInfo, it simply puts the names you specified in the order.

Have you try creating the CSR with CertificationRequestBuilder? You can add both names in and see if LE would issue the certificate.

**Comment by batooo** [comment]
If the order is for *.example.com and CSR CN is example.com = Order includes different number of names than CSR specifies.

If the order is for *.example.com and CSR CN is *.example.com = works but certificate does not have example.com as SAN.

I cannot use CertificationRequestBuilder for v2? Finalize method accept only CsrInfo but CsrInfo does not have SAN property.

I haven't tried to make an order with both hostnames, *.example.com & example.com.

Similar post here: https://community.letsencrypt.org/t/wildcard-names-incomplete/54525/7

**Comment by batooo** [comment]
This is working:

Order: *.example.com, example.com
CSR CN: example.com
=
Certificate CN: example.com
Certificate SAN: *.example.com, example.com

**Comment by fszlin** [comment]
That's great.

You can also use `CertificationRequestBuilder` for v2 to fine tune the CSR, see [here](https://github.com/fszlin/certes/blob/237a40b0cb5a4832ec53f70ba3a951b590831b76/test/Certes.Tests.Integration/AcmeContextIntegration.CertificateByDnsTests.cs#L35-L45) for example.
