### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by XSBen** [fszlin/certes#95]
Does certes support Proxy?

**Comment by fszlin** [comment]
Not at the moment...
I think if I change [`AcmeHttpClient`](https://github.com/fszlin/certes/blob/e5ffd16fa88b5554e1875d186bf63a64bc5506f9/src/Certes/Acme/AcmeHttpClient.cs#L17) to public, you'd be able to pass in a proxied `HttpClient`.

Will it work for you?

**Comment by XSBen** [comment]
@fszlin yes, it think it's good :)

Thank !
