### ISSUE TITLE
Obsolete property in Challenge resource

### ISSUE THREAD

**Issue by JeffreyVerbeek** [fszlin/certes#99]
When using `IChallengeContext.Resource()` the response is a `Challenge` object with a status. If the status comes back invalid there should be an error object. The current [`IList<object> Errors`](https://github.com/fszlin/certes/blob/master/src/Certes/Acme/Resource/Challenge.cs#L55) in the code is always `null` becouse the property has been replaced since draft 10. It is now a single error with subproblems. It can be fould in [section-8](https://tools.ietf.org/html/draft-ietf-acme-acme-12#section-8)

At the moment I am not able to get the reason why validation vailed.
Is this something you want to fix yourself or should I create a Pull request?

**Comment by fszlin** [comment]
Hi @JeffreyVerbeek , thanks for the investigation, and PR would be nice. 👍

**Comment by JeffreyVerbeek** [comment]
This was actually an easy fix. But I did find something else.
You are expecting a `string KeyAuthorization` which I did not find in the spec.
The ` DateTimeOffset? Validated` is not used for some reason. The spec says this property should be used if the validation is valid, but Let's Encrypt does not send it.
Let's Encrypt does send an object `validationRecord` which is not in the spec. Maybe this is something to look into?!

**Comment by fszlin** [comment]
Thanks @JeffreyVerbeek 

* `keyAuthorization` is in draft-09, I think we can mark it obsoleted now.
* `Validated` is in draft-12, so let's keep it.
* LE has always sending `validationRecord` in challenges, if it's useful for you, feel free to create new issue/PR for it.
